#pragma once

#ifndef EXTERNPY
#define EXTERNPY(name) extern _ ## name name
#endif

typedef int (*_EVEPyObject_Cmp)(PyObject *o1, PyObject *o2, int *result);
typedef int (*_EVEPyCallable_Check)(PyObject *o);
typedef PyObject * (*_EVEPyObject_Call)(PyObject *callable_object, PyObject *args, PyObject *kw);
typedef PyObject * (*_EVEPyObject_CallObject)(PyObject *callable_object, PyObject *args);
typedef PyObject * (*_EVEPyObject_CallFunction)(PyObject *callable_object, char *format, ...);
typedef PyObject * (*_EVEPyObject_CallMethod)(PyObject *o, char *m, char *format, ...);
typedef PyObject * (*_EVE_PyObject_CallFunction_SizeT)(PyObject *callable, char *format, ...);
typedef PyObject * (*_EVE_PyObject_CallMethod_SizeT)(PyObject *o, char *name, char *format, ...);
typedef PyObject * (*_EVEPyObject_CallFunctionObjArgs)(PyObject *callable, ...);
typedef PyObject * (*_EVEPyObject_CallMethodObjArgs)(PyObject *o, PyObject *m, ...);
typedef PyObject * (*_EVEPyObject_Type)(PyObject *o);
typedef Py_ssize_t (*_EVEPyObject_Size)(PyObject *o);
typedef Py_ssize_t (*_EVEPyObject_Length)(PyObject *o);
typedef Py_ssize_t (*_EVE_PyObject_LengthHint)(PyObject *o, Py_ssize_t);
typedef PyObject * (*_EVEPyObject_GetItem)(PyObject *o, PyObject *key);
typedef int (*_EVEPyObject_SetItem)(PyObject *o, PyObject *key, PyObject *v);
typedef int (*_EVEPyObject_DelItemString)(PyObject *o, char *key);
typedef int (*_EVEPyObject_DelItem)(PyObject *o, PyObject *key);
typedef int (*_EVEPyObject_AsCharBuffer)(PyObject *obj, const char **buffer, Py_ssize_t *buffer_len);
typedef int (*_EVEPyObject_CheckReadBuffer)(PyObject *obj);
typedef int (*_EVEPyObject_AsReadBuffer)(PyObject *obj, const void **buffer, Py_ssize_t *buffer_len);
typedef int (*_EVEPyObject_AsWriteBuffer)(PyObject *obj, void **buffer, Py_ssize_t *buffer_len);
typedef int (*_EVEPyObject_GetBuffer)(PyObject *obj, Py_buffer *view, int flags);
typedef void * (*_EVEPyBuffer_GetPointer)(Py_buffer *view, Py_ssize_t *indices);
typedef int (*_EVEPyBuffer_SizeFromFormat)(const char *);
typedef int (*_EVEPyBuffer_ToContiguous)(void *buf, Py_buffer *view, Py_ssize_t len, char fort);
typedef int (*_EVEPyBuffer_FromContiguous)(Py_buffer *view, void *buf, Py_ssize_t len, char fort);
typedef int (*_EVEPyObject_CopyData)(PyObject *dest, PyObject *src);
typedef int (*_EVEPyBuffer_IsContiguous)(Py_buffer *view, char fort);
typedef void (*_EVEPyBuffer_FillContiguousStrides)(int ndims, Py_ssize_t *shape, Py_ssize_t *strides, int itemsize, char fort);
typedef int (*_EVEPyBuffer_FillInfo)(Py_buffer *view, PyObject *o, void *buf, Py_ssize_t len, int readonly, int flags);
typedef void (*_EVEPyBuffer_Release)(Py_buffer *view);
typedef PyObject * (*_EVEPyObject_Format)(PyObject* obj, PyObject *format_spec);
typedef PyObject * (*_EVEPyObject_GetIter)(PyObject *);
typedef PyObject * (*_EVEPyIter_Next)(PyObject *);
typedef int (*_EVEPyNumber_Check)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Add)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Subtract)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Multiply)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Divide)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_FloorDivide)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_TrueDivide)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Remainder)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Divmod)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Power)(PyObject *o1, PyObject *o2, PyObject *o3);
typedef PyObject * (*_EVEPyNumber_Negative)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Positive)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Absolute)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Invert)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Lshift)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Rshift)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_And)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Xor)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Or)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_Index)(PyObject *o);
typedef Py_ssize_t (*_EVEPyNumber_AsSsize_t)(PyObject *o, PyObject *exc);
typedef PyObject * (*_EVE_PyNumber_ConvertIntegralToInt)(PyObject *integral, const char* error_format);
typedef PyObject * (*_EVEPyNumber_Int)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Long)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_Float)(PyObject *o);
typedef PyObject * (*_EVEPyNumber_InPlaceAdd)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceSubtract)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceMultiply)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceDivide)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceFloorDivide)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceTrueDivide)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceRemainder)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlacePower)(PyObject *o1, PyObject *o2, PyObject *o3);
typedef PyObject * (*_EVEPyNumber_InPlaceLshift)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceRshift)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceAnd)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceXor)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_InPlaceOr)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPyNumber_ToBase)(PyObject *n, int base);
typedef int (*_EVEPySequence_Check)(PyObject *o);
typedef Py_ssize_t (*_EVEPySequence_Size)(PyObject *o);
typedef Py_ssize_t (*_EVEPySequence_Length)(PyObject *o);
typedef PyObject * (*_EVEPySequence_Concat)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPySequence_Repeat)(PyObject *o, Py_ssize_t count);
typedef PyObject * (*_EVEPySequence_GetItem)(PyObject *o, Py_ssize_t i);
typedef PyObject * (*_EVEPySequence_GetSlice)(PyObject *o, Py_ssize_t i1, Py_ssize_t i2);
typedef int (*_EVEPySequence_SetItem)(PyObject *o, Py_ssize_t i, PyObject *v);
typedef int (*_EVEPySequence_DelItem)(PyObject *o, Py_ssize_t i);
typedef int (*_EVEPySequence_SetSlice)(PyObject *o, Py_ssize_t i1, Py_ssize_t i2, PyObject *v);
typedef int (*_EVEPySequence_DelSlice)(PyObject *o, Py_ssize_t i1, Py_ssize_t i2);
typedef PyObject * (*_EVEPySequence_Tuple)(PyObject *o);
typedef PyObject * (*_EVEPySequence_List)(PyObject *o);
typedef PyObject * (*_EVEPySequence_Fast)(PyObject *o, const char* m);
typedef Py_ssize_t (*_EVEPySequence_Count)(PyObject *o, PyObject *value);
typedef int (*_EVEPySequence_Contains)(PyObject *seq, PyObject *ob);
typedef Py_ssize_t (*_EVE_PySequence_IterSearch)(PyObject *seq, PyObject *obj, int operation);
typedef int (*_EVEPySequence_In)(PyObject *o, PyObject *value);
typedef Py_ssize_t (*_EVEPySequence_Index)(PyObject *o, PyObject *value);
typedef PyObject * (*_EVEPySequence_InPlaceConcat)(PyObject *o1, PyObject *o2);
typedef PyObject * (*_EVEPySequence_InPlaceRepeat)(PyObject *o, Py_ssize_t count);
typedef int (*_EVEPyMapping_Check)(PyObject *o);
typedef Py_ssize_t (*_EVEPyMapping_Size)(PyObject *o);
typedef Py_ssize_t (*_EVEPyMapping_Length)(PyObject *o);
typedef int (*_EVEPyMapping_HasKeyString)(PyObject *o, char *key);
typedef int (*_EVEPyMapping_HasKey)(PyObject *o, PyObject *key);
typedef PyObject * (*_EVEPyMapping_GetItemString)(PyObject *o, char *key);
typedef int (*_EVEPyMapping_SetItemString)(PyObject *o, char *key, PyObject *value);
typedef int (*_EVEPyObject_IsInstance)(PyObject *object, PyObject *typeorclass);
typedef int (*_EVEPyObject_IsSubclass)(PyObject *object, PyObject *typeorclass);
typedef int (*_EVE_PyObject_RealIsInstance)(PyObject *inst, PyObject *cls);
typedef int (*_EVE_PyObject_RealIsSubclass)(PyObject *derived, PyObject *cls);
typedef void (*_EVE_Py_add_one_to_index_F)(int nd, Py_ssize_t *index, const Py_ssize_t *shape);
typedef void (*_EVE_Py_add_one_to_index_C)(int nd, Py_ssize_t *index, const Py_ssize_t *shape);
typedef PyObject * (*_EVEPyBool_FromLong)(long);
typedef PyObject * (*_EVEPyBuffer_FromObject)(PyObject *base, Py_ssize_t offset, Py_ssize_t size);
typedef PyObject * (*_EVEPyBuffer_FromReadWriteObject)(PyObject *base, Py_ssize_t offset, Py_ssize_t size);
typedef PyObject * (*_EVEPyBuffer_FromMemory)(void *ptr, Py_ssize_t size);
typedef PyObject * (*_EVEPyBuffer_FromReadWriteMemory)(void *ptr, Py_ssize_t size);
typedef PyObject * (*_EVEPyBuffer_New)(Py_ssize_t size);
typedef PyObject * (*_EVEPyByteArray_FromObject)(PyObject *);
typedef PyObject * (*_EVEPyByteArray_Concat)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyByteArray_FromStringAndSize)(const char *, Py_ssize_t);
typedef Py_ssize_t (*_EVEPyByteArray_Size)(PyObject *);
typedef char * (*_EVEPyByteArray_AsString)(PyObject *);
typedef int (*_EVEPyByteArray_Resize)(PyObject *, Py_ssize_t);
typedef PyObject * (*_EVEPyCell_New)(PyObject *);
typedef PyObject * (*_EVEPyCell_Get)(PyObject *);
typedef int (*_EVEPyCell_Set)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyEval_CallObjectWithKeywords)(PyObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVEPyEval_CallFunction)(PyObject *obj, const char *format, ...);
typedef PyObject * (*_EVEPyEval_CallMethod)(PyObject *obj, const char *methodname, const char *format, ...);
typedef void (*_EVEPyEval_SetProfile)(Py_tracefunc, PyObject *);
typedef void (*_EVEPyEval_SetTrace)(Py_tracefunc, PyObject *);
typedef PyObject * (*_EVEPyEval_GetBuiltins)(void);
typedef PyObject * (*_EVEPyEval_GetGlobals)(void);
typedef PyObject * (*_EVEPyEval_GetLocals)(void);
typedef int (*_EVEPyEval_GetRestricted)(void);
typedef int (*_EVEPyEval_MergeCompilerFlags)(PyCompilerFlags *cf);
typedef int (*_EVEPy_FlushLine)(void);
typedef int (*_EVEPy_AddPendingCall)(int );
typedef int (*_EVEPy_MakePendingCalls)(void);
typedef void (*_EVEPy_SetRecursionLimit)(int);
typedef int (*_EVEPy_GetRecursionLimit)(void);
typedef int (*_EVE_Py_CheckRecursiveCall)(const char *where);
typedef PyObject * (*_EVEPyEval_GetCallStats)(PyObject *);
typedef PyObject * (*_EVEPyEval_EvalFrame)(struct _frame *);
typedef PyObject * (*_EVEPyEval_EvalFrameEx)(struct _frame *f, int exc);
typedef PyObject * (*_EVEPyEval_EvalFrame_slp)(struct _frame *f, int exc, PyObject *retval);
typedef PyObject * (*_EVEPyEval_EvalFrameEx_slp)(struct _frame *f, int exc, PyObject *retval);
typedef PyThreadState * (*_EVEPyEval_SaveThread)(void);
typedef void (*_EVEPyEval_RestoreThread)(PyThreadState *);
typedef int (*_EVE)(void);
typedef void (*_EVEPyEval_InitThreads)(void);
typedef void (*_EVEPyEval_AcquireLock)(void);
typedef void (*_EVEPyEval_ReleaseLock)(void);
typedef void (*_EVEPyEval_AcquireThread)(PyThreadState *tstate);
typedef void (*_EVEPyEval_ReleaseThread)(PyThreadState *tstate);
typedef void (*_EVEPyEval_ReInitThreads)(void);
typedef int (*_EVE_PyEval_SliceIndex)(PyObject *, Py_ssize_t *);
typedef PyObject * (*_EVEPyClass_New)(PyObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVEPyInstance_New)(PyObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVEPyInstance_NewRaw)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyMethod_New)(PyObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVEPyMethod_Function)(PyObject *);
typedef PyObject * (*_EVEPyMethod_Self)(PyObject *);
typedef PyObject * (*_EVEPyMethod_Class)(PyObject *);
typedef PyObject * (*_EVE_PyInstance_Lookup)(PyObject *pinst, PyObject *name);
typedef int (*_EVEPyClass_IsSubclass)(PyObject *, PyObject *);
typedef int (*_EVEPyMethod_ClearFreeList)(void);
typedef void * (*_EVEPyCObject_AsVoidPtr)(PyObject *);
typedef void * (*_EVEPyCObject_GetDesc)(PyObject *);
typedef void * (*_EVEPyCObject_Import)(char *module_name, char *cobject_name);
typedef int (*_EVEPyCObject_SetVoidPtr)(PyObject *self, void *cobj);
typedef PyCodeObject * (*_EVEPyCode_New)(int, int, int, int, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, int, PyObject *);
typedef int (*_EVEPyCode_Addr2Line)(PyCodeObject *, int);
typedef int (*_EVE_PyCode_CheckLineNumber)(PyCodeObject* co, int lasti, PyAddrPair *bounds);
typedef PyObject* (*_EVE_PyCode_ConstantKey)(PyObject *obj);
typedef PyObject* (*_EVEPyCode_Optimize)(PyObject *code, PyObject* consts, PyObject *names, PyObject *lineno_obj);
typedef int (*_EVEPyCodec_RegisterError)(const char *name, PyObject *error);
typedef PyObject * (*_EVEPyCodec_LookupError)(const char *name);
typedef PyObject * (*_EVEPyCodec_StrictErrors)(PyObject *exc);
typedef PyObject * (*_EVEPyCodec_IgnoreErrors)(PyObject *exc);
typedef PyObject * (*_EVEPyCodec_ReplaceErrors)(PyObject *exc);
typedef PyObject * (*_EVEPyCodec_XMLCharRefReplaceErrors)(PyObject *exc);
typedef PyObject * (*_EVEPyCodec_BackslashReplaceErrors)(PyObject *exc);
typedef PyCodeObject * (*_EVEPyNode_Compile)(struct _node *, const char *);
typedef PyCodeObject * (*_EVEPyAST_Compile)(struct _mod *, const char *, PyCompilerFlags *, PyArena *);
typedef PyFutureFeatures * (*_EVEPyFuture_FromAST)(struct _mod *, const char *);
typedef PyObject * (*_EVEPyComplex_FromCComplex)(Py_complex);
typedef PyObject * (*_EVEPyComplex_FromDoubles)(double real, double imag);
typedef double (*_EVEPyComplex_RealAsDouble)(PyObject *op);
typedef double (*_EVEPyComplex_ImagAsDouble)(PyObject *op);
typedef Py_complex (*_EVEPyComplex_AsCComplex)(PyObject *op);
typedef PyObject * (*_EVE_PyComplex_FormatAdvanced)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len);
typedef PyObject * (*_EVEPyDescr_NewMethod)(PyTypeObject *, PyMethodDef *);
typedef PyObject * (*_EVEPyDescr_NewClassMethod)(PyTypeObject *, PyMethodDef *);
typedef PyObject * (*_EVEPyDescr_NewMember)(PyTypeObject *, struct PyMemberDef *);
typedef PyObject * (*_EVEPyDescr_NewGetSet)(PyTypeObject *, struct PyGetSetDef *);
typedef PyObject * (*_EVEPyDescr_NewWrapper)(PyTypeObject *, struct wrapperbase *, void *);
typedef PyObject * (*_EVEPyDictProxy_New)(PyObject *);
typedef PyObject * (*_EVEPyWrapper_New)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyDict_New)(void);
typedef PyObject * (*_EVEPyDict_GetItem)(PyObject *mp, PyObject *key);
typedef PyObject * (*_EVE_PyDict_GetItemWithError)(PyObject *mp, PyObject *key);
typedef int (*_EVEPyDict_SetItem)(PyObject *mp, PyObject *key, PyObject *item);
typedef int (*_EVEPyDict_DelItem)(PyObject *mp, PyObject *key);
typedef void (*_EVEPyDict_Clear)(PyObject *mp);
typedef int (*_EVEPyDict_Next)(PyObject *mp, Py_ssize_t *pos, PyObject **key, PyObject **value);
typedef int (*_EVE_PyDict_Next)(PyObject *mp, Py_ssize_t *pos, PyObject **key, PyObject **value, long *hash);
typedef PyObject * (*_EVEPyDict_Keys)(PyObject *mp);
typedef PyObject * (*_EVEPyDict_Values)(PyObject *mp);
typedef PyObject * (*_EVEPyDict_Items)(PyObject *mp);
typedef Py_ssize_t (*_EVEPyDict_Size)(PyObject *mp);
typedef PyObject * (*_EVEPyDict_Copy)(PyObject *mp);
typedef int (*_EVEPyDict_Contains)(PyObject *mp, PyObject *key);
typedef int (*_EVE_PyDict_Contains)(PyObject *mp, PyObject *key, long hash);
typedef PyObject * (*_EVE_PyDict_NewPresized)(Py_ssize_t minused);
typedef void (*_EVE_PyDict_MaybeUntrack)(PyObject *mp);
typedef int (*_EVEPyDict_Update)(PyObject *mp, PyObject *other);
typedef int (*_EVEPyDict_Merge)(PyObject *mp, PyObject *other, int override);
typedef int (*_EVEPyDict_MergeFromSeq2)(PyObject *d, PyObject *seq2, int override);
typedef PyObject * (*_EVEPyDict_GetItemString)(PyObject *dp, const char *key);
typedef int (*_EVEPyDict_SetItemString)(PyObject *dp, const char *key, PyObject *item);
typedef int (*_EVEPyDict_DelItemString)(PyObject *dp, const char *key);
typedef double (*_EVE_Py_dg_strtod)(const char *str, char **ptr);
typedef char * (*_EVE_Py_dg_dtoa)(double d, int mode, int ndigits, int *decpt, int *sign, char **rve);
typedef void (*_EVE_Py_dg_freedtoa)(char *s);
typedef PyObject * (*_EVEPyEval_EvalCode)(PyCodeObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVEPyEval_EvalCodeEx)(PyCodeObject *co, PyObject *globals, PyObject *locals, PyObject **args, int argc, PyObject **kwds, int kwdc, PyObject **defs, int defc, PyObject *closure);
typedef PyObject * (*_EVE_PyEval_CallTracing)(PyObject *func, PyObject *args);
typedef PyObject * (*_EVEPyFile_FromString)(char *, char *);
typedef void (*_EVEPyFile_SetBufSize)(PyObject *, int);
typedef int (*_EVEPyFile_SetEncoding)(PyObject *, const char *);
typedef int (*_EVEPyFile_SetEncodingAndErrors)(PyObject *, const char *, char *errors);
typedef PyObject * (*_EVEPyFile_FromFile)(FILE *, char *, char *, int );
typedef FILE * (*_EVEPyFile_AsFile)(PyObject *);
typedef void (*_EVEPyFile_IncUseCount)(PyFileObject *);
typedef void (*_EVEPyFile_DecUseCount)(PyFileObject *);
typedef PyObject * (*_EVEPyFile_Name)(PyObject *);
typedef PyObject * (*_EVEPyFile_GetLine)(PyObject *, int);
typedef int (*_EVEPyFile_WriteObject)(PyObject *, PyObject *, int);
typedef int (*_EVEPyFile_SoftSpace)(PyObject *, int);
typedef int (*_EVEPyFile_WriteString)(const char *, PyObject *);
typedef int (*_EVEPyObject_AsFileDescriptor)(PyObject *);
typedef double (*_EVEPyFloat_GetMax)(void);
typedef double (*_EVEPyFloat_GetMin)(void);
typedef PyObject * (*_EVEPyFloat_GetInfo)(void);
typedef PyObject * (*_EVEPyFloat_FromString)(PyObject*, char** junk);
typedef PyObject * (*_EVEPyFloat_FromDouble)(double);
typedef double (*_EVEPyFloat_AsDouble)(PyObject *);
typedef void (*_EVEPyFloat_AsReprString)(char*, PyFloatObject *v);
typedef void (*_EVEPyFloat_AsString)(char*, PyFloatObject *v);
typedef int (*_EVE_PyFloat_Pack4)(double x, unsigned char *p, int le);
typedef int (*_EVE_PyFloat_Pack8)(double x, unsigned char *p, int le);
typedef int (*_EVE_PyFloat_Digits)(char *buf, double v, int *signum);
typedef void (*_EVE_PyFloat_DigitsInit)(void);
typedef double (*_EVE_PyFloat_Unpack4)(const unsigned char *p, int le);
typedef double (*_EVE_PyFloat_Unpack8)(const unsigned char *p, int le);
typedef int (*_EVEPyFloat_ClearFreeList)(void);
typedef PyObject * (*_EVE_PyFloat_FormatAdvanced)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len);
typedef PyObject * (*_EVE_Py_double_round)(double x, int ndigits);
typedef PyFrameObject * (*_EVEPyFrame_New)(PyThreadState *, PyCodeObject *, PyObject *, PyObject *);
typedef void (*_EVEPyFrame_BlockSetup)(PyFrameObject *, int, int, int);
typedef PyTryBlock * (*_EVEPyFrame_BlockPop)(PyFrameObject *);
typedef PyObject ** (*_EVEPyFrame_ExtendStack)(PyFrameObject *, int, int);
typedef void (*_EVEPyFrame_LocalsToFast)(PyFrameObject *, int);
typedef void (*_EVEPyFrame_FastToLocals)(PyFrameObject *);
typedef int (*_EVEPyFrame_ClearFreeList)(void);
typedef int (*_EVEPyFrame_GetLineNumber)(PyFrameObject *);
typedef PyObject * (*_EVEPyFunction_New)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyFunction_GetCode)(PyObject *);
typedef PyObject * (*_EVEPyFunction_GetGlobals)(PyObject *);
typedef PyObject * (*_EVEPyFunction_GetModule)(PyObject *);
typedef PyObject * (*_EVEPyFunction_GetDefaults)(PyObject *);
typedef int (*_EVEPyFunction_SetDefaults)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyFunction_GetClosure)(PyObject *);
typedef int (*_EVEPyFunction_SetClosure)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyClassMethod_New)(PyObject *);
typedef PyObject * (*_EVEPyStaticMethod_New)(PyObject *);
typedef PyObject * (*_EVEPyGen_New)(struct _frame *);
typedef int (*_EVEPyGen_NeedsFinalizing)(PyGenObject *);
typedef long (*_EVEPyImport_GetMagicNumber)(void);
typedef PyObject * (*_EVEPyImport_ExecCodeModule)(char *name, PyObject *co);
typedef PyObject * (*_EVEPyImport_ExecCodeModuleEx)(char *name, PyObject *co, char *pathname);
typedef PyObject * (*_EVEPyImport_GetModuleDict)(void);
typedef PyObject * (*_EVEPyImport_AddModule)(const char *name);
typedef PyObject * (*_EVEPyImport_ImportModule)(const char *name);
typedef PyObject * (*_EVEPyImport_ImportModuleNoBlock)(const char *);
typedef PyObject * (*_EVEPyImport_ImportModuleLevel)(char *name, PyObject *globals, PyObject *locals, PyObject *fromlist, int level);
typedef PyObject * (*_EVEPyImport_GetImporter)(PyObject *path);
typedef PyObject * (*_EVEPyImport_Import)(PyObject *name);
typedef PyObject * (*_EVEPyImport_ReloadModule)(PyObject *m);
typedef void (*_EVEPyImport_Cleanup)(void);
typedef int (*_EVEPyImport_ImportFrozenModule)(char *);
typedef void (*_EVE_PyImport_AcquireLock)(void);
typedef int (*_EVE_PyImport_ReleaseLock)(void);
typedef int (*_EVE_PyImport_IsScript)(struct filedescr *);
typedef void (*_EVE_PyImport_ReInitLock)(void);
typedef PyObject * (*_EVE_PyImport_FindExtension)(char *, char *);
typedef PyObject * (*_EVE_PyImport_FixupExtension)(char *, char *);
typedef PyObject * (*_EVEPyInt_FromString)(char*, char**, int);
typedef PyObject * (*_EVEPyInt_FromUnicode)(Py_UNICODE*, Py_ssize_t, int);
typedef PyObject * (*_EVEPyInt_FromLong)(long);
typedef PyObject * (*_EVEPyInt_FromSize_t)(size_t);
typedef PyObject * (*_EVEPyInt_FromSsize_t)(Py_ssize_t);
typedef long (*_EVEPyInt_AsLong)(PyObject *);
typedef Py_ssize_t (*_EVEPyInt_AsSsize_t)(PyObject *);
typedef int (*_EVE_PyInt_AsInt)(PyObject *);
typedef long (*_EVEPyInt_GetMax)(void);
typedef long (*_EVEPyOS_strtol)(char *, char **, int);
typedef int (*_EVEPyInt_ClearFreeList)(void);
typedef PyObject* (*_EVE_PyInt_Format)(PyIntObject* v, int base, int newstyle);
typedef PyObject * (*_EVE_PyInt_FormatAdvanced)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len);
typedef int (*_EVEPyOS_InterruptOccurred)(void);
typedef void (*_EVEPyOS_InitInterrupts)(void);
typedef void (*_EVEPyOS_AfterFork)(void);
typedef PyObject * (*_EVEPySeqIter_New)(PyObject *);
typedef PyObject * (*_EVEPyCallIter_New)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyList_New)(Py_ssize_t size);
typedef Py_ssize_t (*_EVEPyList_Size)(PyObject *);
typedef PyObject * (*_EVEPyList_GetItem)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyList_SetItem)(PyObject *, Py_ssize_t, PyObject *);
typedef int (*_EVEPyList_Insert)(PyObject *, Py_ssize_t, PyObject *);
typedef int (*_EVEPyList_Append)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyList_GetSlice)(PyObject *, Py_ssize_t, Py_ssize_t);
typedef int (*_EVEPyList_SetSlice)(PyObject *, Py_ssize_t, Py_ssize_t, PyObject *);
typedef int (*_EVEPyList_Sort)(PyObject *);
typedef int (*_EVEPyList_Reverse)(PyObject *);
typedef PyObject * (*_EVEPyList_AsTuple)(PyObject *);
typedef PyObject * (*_EVE_PyList_Extend)(PyListObject *, PyObject *);
typedef PyLongObject * (*_EVE_PyLong_New)(Py_ssize_t);
typedef PyObject * (*_EVE_PyLong_Copy)(PyLongObject *src);
typedef PyObject * (*_EVEPyLong_FromLong)(long);
typedef PyObject * (*_EVEPyLong_FromUnsignedLong)(unsigned long);
typedef PyObject * (*_EVEPyLong_FromDouble)(double);
typedef PyObject * (*_EVEPyLong_FromSize_t)(size_t);
typedef PyObject * (*_EVEPyLong_FromSsize_t)(Py_ssize_t);
typedef long (*_EVEPyLong_AsLong)(PyObject *);
typedef long (*_EVEPyLong_AsLongAndOverflow)(PyObject *, int *);
typedef Py_ssize_t (*_EVEPyLong_AsSsize_t)(PyObject *);
typedef int (*_EVE_PyLong_AsInt)(PyObject *);
typedef PyObject * (*_EVEPyLong_GetInfo)(void);
typedef double (*_EVE_PyLong_Frexp)(PyLongObject *a, Py_ssize_t *e);
typedef double (*_EVEPyLong_AsDouble)(PyObject *);
typedef PyObject * (*_EVEPyLong_FromVoidPtr)(void *);
typedef void * (*_EVEPyLong_AsVoidPtr)(PyObject *);
typedef PyObject * (*_EVEPyLong_FromLongLong)(PY_LONG_LONG);
typedef PyObject * (*_EVEPyLong_FromUnsignedLongLong)(unsigned PY_LONG_LONG);
typedef PY_LONG_LONG (*_EVEPyLong_AsLongLong)(PyObject *);
typedef PY_LONG_LONG (*_EVEPyLong_AsLongLongAndOverflow)(PyObject *, int *);
typedef PyObject * (*_EVEPyLong_FromString)(char *, char **, int);
typedef PyObject * (*_EVEPyLong_FromUnicode)(Py_UNICODE*, Py_ssize_t, int);
typedef int (*_EVE_PyLong_Sign)(PyObject *v);
typedef size_t (*_EVE_PyLong_NumBits)(PyObject *v);
typedef PyObject * (*_EVE_PyLong_FromByteArray)(const unsigned char* bytes, size_t n, int little_endian, int is_signed);
typedef int (*_EVE_PyLong_AsByteArray)(PyLongObject* v, unsigned char* bytes, size_t n, int little_endian, int is_signed);
typedef PyObject * (*_EVE_PyLong_Format)(PyObject *aa, int base, int addL, int newstyle);
typedef PyObject * (*_EVE_PyLong_FormatAdvanced)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len);
typedef void (*_EVEPyMarshal_WriteLongToFile)(long, FILE *, int);
typedef void (*_EVEPyMarshal_WriteObjectToFile)(PyObject *, FILE *, int);
typedef PyObject * (*_EVEPyMarshal_WriteObjectToString)(PyObject *, int);
typedef long (*_EVEPyMarshal_ReadLongFromFile)(FILE *);
typedef int (*_EVEPyMarshal_ReadShortFromFile)(FILE *);
typedef PyObject * (*_EVEPyMarshal_ReadObjectFromFile)(FILE *);
typedef PyObject * (*_EVEPyMarshal_ReadLastObjectFromFile)(FILE *);
typedef PyObject * (*_EVEPyMarshal_ReadObjectFromString)(char *, Py_ssize_t);
typedef PyCFunction (*_EVEPyCFunction_GetFunction)(PyObject *);
typedef PyObject * (*_EVEPyCFunction_GetSelf)(PyObject *);
typedef int (*_EVEPyCFunction_GetFlags)(PyObject *);
typedef PyObject * (*_EVEPyCFunction_Call)(PyObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVEPy_FindMethod)(PyMethodDef[], PyObject *, const char *);
typedef int (*_EVEPyCFunction_ClearFreeList)(void);
typedef PyObject * (*_EVE_Py_VaBuildValue_SizeT)(const char *, va_list);
typedef int (*_EVEPyArg_Parse)(PyObject *, const char *, ...);
typedef int (*_EVEPyArg_ParseTuple)(PyObject *, const char *, ...);
typedef int (*_EVEPyArg_ParseTupleAndKeywords)(PyObject *, PyObject *, const char *, char **, ...);
typedef int (*_EVEPyArg_UnpackTuple)(PyObject *, const char *, Py_ssize_t, Py_ssize_t, ...);
typedef PyObject * (*_EVEPy_BuildValue)(const char *, ...);
typedef PyObject * (*_EVE_Py_BuildValue_SizeT)(const char *, ...);
typedef int (*_EVE_PyArg_NoKeywords)(const char *funcname, PyObject *kw);
typedef int (*_EVEPyArg_VaParse)(PyObject *, const char *, va_list);
typedef int (*_EVEPyArg_VaParseTupleAndKeywords)(PyObject *, PyObject *, const char *, char **, va_list);
typedef PyObject * (*_EVEPy_VaBuildValue)(const char *, va_list);
typedef int (*_EVEPyModule_AddObject)(PyObject *, const char *, PyObject *);
typedef int (*_EVEPyModule_AddIntConstant)(PyObject *, const char *, long);
typedef int (*_EVEPyModule_AddStringConstant)(PyObject *, const char *, const char *);
typedef PyObject * (*_EVEPy_InitModule4)(const char *name, PyMethodDef *methods, const char *doc, PyObject *self, int apiver);
typedef PyObject * (*_EVEPyModule_New)(const char *);
typedef PyObject * (*_EVEPyModule_GetDict)(PyObject *);
typedef char * (*_EVEPyModule_GetName)(PyObject *);
typedef char * (*_EVEPyModule_GetFilename)(PyObject *);
typedef void (*_EVE_PyModule_Clear)(PyObject *);
typedef int (*_EVEPyType_IsSubtype)(PyTypeObject *, PyTypeObject *);
typedef int (*_EVEPyType_Ready)(PyTypeObject *);
typedef PyObject * (*_EVEPyType_GenericAlloc)(PyTypeObject *, Py_ssize_t);
typedef PyObject * (*_EVEPyType_GenericNew)(PyTypeObject *, PyObject *, PyObject *);
typedef PyObject * (*_EVE_PyType_Lookup)(PyTypeObject *, PyObject *);
typedef PyObject * (*_EVE_PyObject_LookupSpecial)(PyObject *, char *, PyObject **);
typedef void (*_EVEPyType_Modified)(PyTypeObject *);
typedef int (*_EVEPyObject_Print)(PyObject *, FILE *, int);
typedef void (*_EVE_PyObject_Dump)(PyObject *);
typedef PyObject * (*_EVEPyObject_Repr)(PyObject *);
typedef PyObject * (*_EVE_PyObject_Str)(PyObject *);
typedef PyObject * (*_EVEPyObject_Str)(PyObject *);
typedef PyObject * (*_EVEPyObject_Unicode)(PyObject *);
typedef int (*_EVEPyObject_Compare)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyObject_RichCompare)(PyObject *, PyObject *, int);
typedef int (*_EVEPyObject_RichCompareBool)(PyObject *, PyObject *, int);
typedef PyObject * (*_EVEPyObject_GetAttrString)(PyObject *, const char *);
typedef int (*_EVEPyObject_SetAttrString)(PyObject *, const char *, PyObject *);
typedef int (*_EVEPyObject_HasAttrString)(PyObject *, const char *);
typedef PyObject * (*_EVEPyObject_GetAttr)(PyObject *, PyObject *);
typedef int (*_EVEPyObject_SetAttr)(PyObject *, PyObject *, PyObject *);
typedef int (*_EVEPyObject_HasAttr)(PyObject *, PyObject *);
typedef PyObject ** (*_EVE_PyObject_GetDictPtr)(PyObject *);
typedef PyObject * (*_EVEPyObject_SelfIter)(PyObject *);
typedef PyObject * (*_EVE_PyObject_NextNotImplemented)(PyObject *);
typedef PyObject * (*_EVEPyObject_GenericGetAttr)(PyObject *, PyObject *);
typedef int (*_EVEPyObject_GenericSetAttr)(PyObject *, PyObject *, PyObject *);
typedef long (*_EVEPyObject_Hash)(PyObject *);
typedef long (*_EVEPyObject_HashNotImplemented)(PyObject *);
typedef int (*_EVEPyObject_IsTrue)(PyObject *);
typedef int (*_EVEPyObject_Not)(PyObject *);
typedef int (*_EVEPyCallable_Check)(PyObject *);
typedef int (*_EVEPyNumber_Coerce)(PyObject **, PyObject **);
typedef int (*_EVEPyNumber_CoerceEx)(PyObject **, PyObject **);
typedef void (*_EVEPyObject_ClearWeakRefs)(PyObject *);
typedef PyObject * (*_EVEPyObject_Dir)(PyObject *);
typedef int (*_EVEPy_ReprEnter)(PyObject *);
typedef void (*_EVEPy_ReprLeave)(PyObject *);
typedef long (*_EVE_Py_HashDouble)(double);
typedef long (*_EVE_Py_HashPointer)(void*);
typedef void (*_EVE_Py_NegativeRefcount)(const char *fname, int lineno, PyObject *op);
typedef PyObject * (*_EVE_PyDict_Dummy)(void);
typedef PyObject * (*_EVE_PySet_Dummy)(void);
typedef Py_ssize_t (*_EVE_Py_GetRefTotal)(void);
typedef void (*_EVEinc_count)(PyTypeObject *);
typedef void (*_EVEdec_count)(PyTypeObject *);
typedef void (*_EVE_Py_NewReference)(PyObject *);
typedef void (*_EVE_Py_ForgetReference)(PyObject *);
typedef void (*_EVE_Py_Dealloc)(PyObject *);
typedef void (*_EVE_Py_PrintReferences)(FILE *);
typedef void (*_EVE_Py_PrintReferenceAddresses)(FILE *);
typedef void (*_EVE_Py_AddToAllObjects)(PyObject *, int force);
typedef void (*_EVEPy_IncRef)(PyObject *);
typedef void (*_EVEPy_DecRef)(PyObject *);
typedef void (*_EVE_PyTrash_deposit_object)(PyObject*);
typedef void (*_EVE_PyTrash_destroy_chain)(void);
typedef void (*_EVE_PyTrash_thread_deposit_object)(PyObject*);
typedef void (*_EVE_PyTrash_thread_destroy_chain)(void);
typedef void * (*_EVEPyObject_Malloc)(size_t);
typedef void * (*_EVEPyObject_Realloc)(void *, size_t);
typedef void (*_EVEPyObject_Free)(void *);
typedef void * (*_EVE_PyObject_DebugMalloc)(size_t nbytes);
typedef void * (*_EVE_PyObject_DebugRealloc)(void *p, size_t nbytes);
typedef void (*_EVE_PyObject_DebugFree)(void *p);
typedef void (*_EVE_PyObject_DebugDumpAddress)(const void *p);
typedef void (*_EVE_PyObject_DebugCheckAddress)(const void *p);
typedef void (*_EVE_PyObject_DebugMallocStats)(void);
typedef void * (*_EVE_PyObject_DebugMallocApi)(char api, size_t nbytes);
typedef void * (*_EVE_PyObject_DebugReallocApi)(char api, void *p, size_t nbytes);
typedef void (*_EVE_PyObject_DebugFreeApi)(char api, void *p);
typedef void (*_EVE_PyObject_DebugCheckAddressApi)(char api, const void *p);
typedef void * (*_EVE_PyMem_DebugMalloc)(size_t nbytes);
typedef void * (*_EVE_PyMem_DebugRealloc)(void *p, size_t nbytes);
typedef void (*_EVE_PyMem_DebugFree)(void *p);
typedef PyObject * (*_EVEPyObject_Init)(PyObject *, PyTypeObject *);
typedef PyVarObject * (*_EVEPyObject_InitVar)(PyVarObject *, PyTypeObject *, Py_ssize_t);
typedef PyObject * (*_EVE_PyObject_New)(PyTypeObject *);
typedef PyVarObject * (*_EVE_PyObject_NewVar)(PyTypeObject *, Py_ssize_t);
typedef Py_ssize_t (*_EVEPyGC_Collect)(void);
typedef PyVarObject * (*_EVE_PyObject_GC_Resize)(PyVarObject *, Py_ssize_t);
typedef PyObject * (*_EVE_PyObject_GC_Malloc)(size_t);
typedef PyObject * (*_EVE_PyObject_GC_New)(PyTypeObject *);
typedef PyVarObject * (*_EVE_PyObject_GC_NewVar)(PyTypeObject *, Py_ssize_t);
typedef void (*_EVEPyObject_GC_Track)(void *);
typedef void (*_EVEPyObject_GC_UnTrack)(void *);
typedef void (*_EVEPyObject_GC_Del)(void *);
typedef void (*_EVEPyObject_GC_Collectable)(PyObject *, visitproc, void*, int);
typedef void (*_EVEPySys_WriteStdout)(const char *format, ...);
typedef void (*_EVEPySys_WriteStderr)(const char *format, ...);
typedef PyArena * (*_EVEPyArena_New)(void);
typedef void (*_EVEPyArena_Free)(PyArena *);
typedef void * (*_EVEPyArena_Malloc)(PyArena *, size_t size);
typedef int (*_EVEPyArena_AddPyObject)(PyArena *, PyObject *);
typedef PyObject * (*_EVEPyCapsule_New)(void *pointer, const char *name, PyCapsule_Destructor destructor);
typedef void * (*_EVEPyCapsule_GetPointer)(PyObject *capsule, const char *name);
typedef PyCapsule_Destructor (*_EVEPyCapsule_GetDestructor)(PyObject *capsule);
typedef void * (*_EVEPyCapsule_GetContext)(PyObject *capsule);
typedef int (*_EVEPyCapsule_IsValid)(PyObject *capsule, const char *name);
typedef int (*_EVEPyCapsule_SetPointer)(PyObject *capsule, void *pointer);
typedef int (*_EVEPyCapsule_SetDestructor)(PyObject *capsule, PyCapsule_Destructor destructor);
typedef int (*_EVEPyCapsule_SetName)(PyObject *capsule, const char *name);
typedef int (*_EVEPyCapsule_SetContext)(PyObject *capsule, void *context);
typedef void * (*_EVEPyCapsule_Import)(const char *name, int no_block);
typedef void (*_EVEPy_FatalError)(const char *message);
typedef void (*_EVEPyErr_SetNone)(PyObject *);
typedef void (*_EVEPyErr_SetObject)(PyObject *, PyObject *);
typedef void (*_EVEPyErr_SetString)(PyObject *, const char *);
typedef PyObject * (*_EVEPyErr_Occurred)(void);
typedef void (*_EVEPyErr_Clear)(void);
typedef void (*_EVEPyErr_Fetch)(PyObject **, PyObject **, PyObject **);
typedef void (*_EVEPyErr_Restore)(PyObject *, PyObject *, PyObject *);
typedef int (*_EVEPyErr_GivenExceptionMatches)(PyObject *, PyObject *);
typedef int (*_EVEPyErr_ExceptionMatches)(PyObject *);
typedef void (*_EVEPyErr_NormalizeException)(PyObject**, PyObject**, PyObject**);
typedef void (*_EVE_PyErr_ReplaceException)(PyObject *, PyObject *, PyObject *);
typedef int (*_EVEPyErr_BadArgument)(void);
typedef PyObject * (*_EVEPyErr_NoMemory)(void);
typedef PyObject * (*_EVEPyErr_SetFromErrno)(PyObject *);
typedef PyObject * (*_EVEPyErr_SetFromErrnoWithFilenameObject)(PyObject *, PyObject *);
typedef PyObject * (*_EVEPyErr_SetFromErrnoWithFilename)(PyObject *, const char *);
typedef PyObject * (*_EVEPyErr_SetFromErrnoWithUnicodeFilename)(PyObject *, const Py_UNICODE *);
typedef PyObject * (*_EVEPyErr_Format)(PyObject *, const char *, ...);
typedef PyObject * (*_EVEPyErr_SetFromWindowsErrWithFilenameObject)(int, const char *);
typedef PyObject * (*_EVEPyErr_SetFromWindowsErrWithFilename)(int, const char *);
typedef PyObject * (*_EVEPyErr_SetFromWindowsErrWithUnicodeFilename)(int, const Py_UNICODE *);
typedef PyObject * (*_EVEPyErr_SetFromWindowsErr)(int);
typedef PyObject * (*_EVEPyErr_SetExcFromWindowsErrWithFilenameObject)(PyObject *,int, PyObject *);
typedef PyObject * (*_EVEPyErr_SetExcFromWindowsErrWithFilename)(PyObject *,int, const char *);
typedef PyObject * (*_EVEPyErr_SetExcFromWindowsErrWithUnicodeFilename)(PyObject *,int, const Py_UNICODE *);
typedef PyObject * (*_EVEPyErr_SetExcFromWindowsErr)(PyObject *, int);
typedef void (*_EVEPyErr_BadInternalCall)(void);
typedef void (*_EVE_PyErr_BadInternalCall)(const char *filename, int lineno);
typedef PyObject * (*_EVEPyErr_NewException)(char *name, PyObject *base, PyObject *dict);
typedef PyObject * (*_EVEPyErr_NewExceptionWithDoc)(char *name, char *doc, PyObject *base, PyObject *dict);
typedef void (*_EVEPyErr_WriteUnraisable)(PyObject *);
typedef int (*_EVEPyErr_CheckSignals)(void);
typedef void (*_EVEPyErr_SetInterrupt)(void);
typedef void (*_EVEPyErr_SyntaxLocation)(const char *, int);
typedef PyObject * (*_EVEPyErr_ProgramText)(const char *, int);
typedef PyObject * (*_EVEPyUnicodeDecodeError_Create)(const char *, const char *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
typedef PyObject * (*_EVEPyUnicodeEncodeError_Create)(const char *, const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
typedef PyObject * (*_EVEPyUnicodeTranslateError_Create)(const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
typedef PyObject * (*_EVEPyUnicodeEncodeError_GetEncoding)(PyObject *);
typedef PyObject * (*_EVEPyUnicodeDecodeError_GetEncoding)(PyObject *);
typedef PyObject * (*_EVEPyUnicodeEncodeError_GetObject)(PyObject *);
typedef PyObject * (*_EVEPyUnicodeDecodeError_GetObject)(PyObject *);
typedef PyObject * (*_EVEPyUnicodeTranslateError_GetObject)(PyObject *);
typedef int (*_EVEPyUnicodeEncodeError_GetStart)(PyObject *, Py_ssize_t *);
typedef int (*_EVEPyUnicodeDecodeError_GetStart)(PyObject *, Py_ssize_t *);
typedef int (*_EVEPyUnicodeTranslateError_GetStart)(PyObject *, Py_ssize_t *);
typedef int (*_EVEPyUnicodeEncodeError_SetStart)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyUnicodeDecodeError_SetStart)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyUnicodeTranslateError_SetStart)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyUnicodeEncodeError_GetEnd)(PyObject *, Py_ssize_t *);
typedef int (*_EVEPyUnicodeDecodeError_GetEnd)(PyObject *, Py_ssize_t *);
typedef int (*_EVEPyUnicodeTranslateError_GetEnd)(PyObject *, Py_ssize_t *);
typedef int (*_EVEPyUnicodeEncodeError_SetEnd)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyUnicodeDecodeError_SetEnd)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyUnicodeTranslateError_SetEnd)(PyObject *, Py_ssize_t);
typedef PyObject * (*_EVEPyUnicodeEncodeError_GetReason)(PyObject *);
typedef PyObject * (*_EVEPyUnicodeDecodeError_GetReason)(PyObject *);
typedef PyObject * (*_EVEPyUnicodeTranslateError_GetReason)(PyObject *);
typedef int (*_EVEPyUnicodeEncodeError_SetReason)(PyObject *, const char *);
typedef int (*_EVEPyUnicodeDecodeError_SetReason)(PyObject *, const char *);
typedef int (*_EVEPyUnicodeTranslateError_SetReason)(PyObject *, const char *);
typedef int (*_EVEPyOS_snprintf)(char *str, size_t size, const char  *format, ...);
typedef int (*_EVEPyOS_vsnprintf)(char *str, size_t size, const char  *format, va_list va);
typedef void (*_EVE_PyOS_ResetGetOpt)(void);
typedef int (*_EVE_PyOS_GetOpt)(int argc, char **argv, char *optstring);
typedef double (*_EVE_Py_force_double)(double);
typedef void (*_EVE_Py_set_387controlword)(unsigned short);
typedef void * (*_EVEPyMem_Malloc)(size_t);
typedef void * (*_EVEPyMem_Realloc)(void *, size_t);
typedef void (*_EVEPyMem_Free)(void *);
typedef PyInterpreterState * (*_EVEPyInterpreterState_New)(void);
typedef void (*_EVEPyInterpreterState_Clear)(PyInterpreterState *);
typedef void (*_EVEPyInterpreterState_Delete)(PyInterpreterState *);
typedef PyThreadState * (*_EVEPyThreadState_New)(PyInterpreterState *);
typedef PyThreadState * (*_EVE_PyThreadState_Prealloc)(PyInterpreterState *);
typedef void (*_EVE_PyThreadState_Init)(PyThreadState *);
typedef void (*_EVEPyThreadState_Clear)(PyThreadState *);
typedef void (*_EVEPyThreadState_Delete)(PyThreadState *);
typedef void (*_EVEPyThreadState_DeleteCurrent)(void);
typedef PyThreadState * (*_EVEPyThreadState_Get)(void);
typedef PyThreadState * (*_EVEPyThreadState_Swap)(PyThreadState *);
typedef PyObject * (*_EVEPyThreadState_GetDict)(void);
typedef int (*_EVEPyThreadState_SetAsyncExc)(long, PyObject *);
typedef PyGILState_STATE (*_EVEPyGILState_Ensure)(void);
typedef void (*_EVEPyGILState_Release)(PyGILState_STATE);
typedef PyThreadState * (*_EVEPyGILState_GetThisThreadState)(void);
typedef PyObject * (*_EVE_PyThread_CurrentFrames)(void);
typedef PyInterpreterState * (*_EVEPyInterpreterState_Head)(void);
typedef PyInterpreterState * (*_EVEPyInterpreterState_Next)(PyInterpreterState *);
typedef PyThreadState * (*_EVEPyInterpreterState_ThreadHead)(PyInterpreterState *);
typedef PyThreadState * (*_EVEPyThreadState_Next)(PyThreadState *);
typedef int (*_EVEPyOS_mystrnicmp)(const char *, const char *, Py_ssize_t);
typedef int (*_EVEPyOS_mystricmp)(const char *, const char *);
typedef double (*_EVEPyOS_ascii_strtod)(const char *str, char **ptr);
typedef double (*_EVEPyOS_ascii_atof)(const char *str);
typedef char * (*_EVEPyOS_ascii_formatd)(char *buffer, size_t buf_len, const char *format, double d);
typedef double (*_EVEPyOS_string_to_double)(const char *str, char **endptr, PyObject *overflow_exception);
typedef char * (*_EVEPyOS_double_to_string)(double val, char format_code, int precision, int flags, int *type);
typedef double (*_EVE_Py_parse_inf_or_nan)(const char *p, char **endptr);
typedef PyObject* (*_EVE_Py_Mangle)(PyObject *p, PyObject *name);
typedef void (*_EVEPy_SetProgramName)(char *);
typedef char * (*_EVEPy_GetProgramName)(void);
typedef void (*_EVEPy_SetPythonHome)(char *);
typedef char * (*_EVEPy_GetPythonHome)(void);
typedef void (*_EVEPy_Initialize)(void);
typedef void (*_EVEPy_InitializeEx)(int);
typedef void (*_EVEPy_Finalize)(void);
typedef int (*_EVEPy_IsInitialized)(void);
typedef PyThreadState * (*_EVEPy_NewInterpreter)(void);
typedef void (*_EVEPy_EndInterpreter)(PyThreadState *);
typedef int (*_EVEPyRun_AnyFileFlags)(FILE *, const char *, PyCompilerFlags *);
typedef int (*_EVEPyRun_AnyFileExFlags)(FILE *, const char *, int, PyCompilerFlags *);
typedef int (*_EVEPyRun_SimpleStringFlags)(const char *, PyCompilerFlags *);
typedef int (*_EVEPyRun_SimpleFileExFlags)(FILE *, const char *, int, PyCompilerFlags *);
typedef int (*_EVEPyRun_InteractiveOneFlags)(FILE *, const char *, PyCompilerFlags *);
typedef int (*_EVEPyRun_InteractiveLoopFlags)(FILE *, const char *, PyCompilerFlags *);
typedef PyObject *(*_EVEPy_CompileStringFlags)(const char *str, const char *filename, int start, PyCompilerFlags *flags);
typedef void (*_EVEPyErr_Print)(void);
typedef void (*_EVEPyErr_PrintEx)(int);
typedef void (*_EVEPyErr_Display)(PyObject *, PyObject *, PyObject *);
typedef int (*_EVEPy_AtExit)(void );
typedef void (*_EVEPy_Exit)(int);
typedef int (*_EVEPy_FdIsInteractive)(FILE *, const char *);
typedef int (*_EVEPy_Main)(int argc, char **argv);
typedef char * (*_EVEPy_GetProgramFullPath)(void);
typedef char * (*_EVEPy_GetPrefix)(void);
typedef char * (*_EVEPy_GetExecPrefix)(void);
typedef char * (*_EVEPy_GetPath)(void);
typedef PyObject * (*_EVE_PyBuiltin_Init)(void);
typedef PyObject * (*_EVE_PySys_Init)(void);
typedef void (*_EVE_PyImport_Init)(void);
typedef void (*_EVE_PyExc_Init)(void);
typedef void (*_EVE_PyImportHooks_Init)(void);
typedef int (*_EVE_PyFrame_Init)(void);
typedef int (*_EVE_PyInt_Init)(void);
typedef int (*_EVE_PyLong_Init)(void);
typedef void (*_EVE_PyFloat_Init)(void);
typedef int (*_EVEPyByteArray_Init)(void);
typedef void (*_EVE_PyRandom_Init)(void);
typedef void (*_EVE_PyExc_Fini)(void);
typedef void (*_EVE_PyImport_Fini)(void);
typedef void (*_EVEPyMethod_Fini)(void);
typedef void (*_EVEPyFrame_Fini)(void);
typedef void (*_EVEPyCFunction_Fini)(void);
typedef void (*_EVEPyDict_Fini)(void);
typedef void (*_EVEPyTuple_Fini)(void);
typedef void (*_EVEPyList_Fini)(void);
typedef void (*_EVEPySet_Fini)(void);
typedef void (*_EVEPyString_Fini)(void);
typedef void (*_EVEPyInt_Fini)(void);
typedef void (*_EVEPyFloat_Fini)(void);
typedef void (*_EVEPyOS_FiniInterrupts)(void);
typedef void (*_EVEPyByteArray_Fini)(void);
typedef void (*_EVE_PyRandom_Fini)(void);
typedef char * (*_EVEPyOS_Readline)(FILE *, FILE *, char *);
typedef int (*_EVEPyOS_CheckStack)(void);
typedef PyOS_sighandler_t (*_EVEPyOS_getsig)(int);
typedef PyOS_sighandler_t (*_EVEPyOS_setsig)(int, PyOS_sighandler_t);
typedef int (*_EVE_PyOS_URandom)(void *buffer, Py_ssize_t size);
typedef void (*_EVEPyThread_init_thread)(void);
typedef long (*_EVEPyThread_start_new_thread)(void );
typedef void (*_EVEPyThread_exit_thread)(void);
typedef long (*_EVEPyThread_get_thread_ident)(void);
typedef size_t (*_EVEPyThread_get_stacksize)(void);
typedef int (*_EVEPyThread_set_stacksize)(size_t);
typedef int (*_EVEPyThread_create_key)(void);
typedef void (*_EVEPyThread_delete_key)(int);
typedef int (*_EVEPyThread_set_key_value)(int, void *);
typedef void * (*_EVEPyThread_get_key_value)(int);
typedef void (*_EVEPyThread_delete_key_value)(int key);
typedef void (*_EVEPyThread_ReInitTLS)(void);
typedef PyObject * (*_EVEPySet_New)(PyObject *);
typedef PyObject * (*_EVEPyFrozenSet_New)(PyObject *);
typedef Py_ssize_t (*_EVEPySet_Size)(PyObject *anyset);
typedef int (*_EVEPySet_Clear)(PyObject *set);
typedef int (*_EVEPySet_Contains)(PyObject *anyset, PyObject *key);
typedef int (*_EVEPySet_Discard)(PyObject *set, PyObject *key);
typedef int (*_EVEPySet_Add)(PyObject *set, PyObject *key);
typedef int (*_EVE_PySet_Next)(PyObject *set, Py_ssize_t *pos, PyObject **key);
typedef int (*_EVE_PySet_NextEntry)(PyObject *set, Py_ssize_t *pos, PyObject **key, long *hash);
typedef PyObject * (*_EVEPySet_Pop)(PyObject *set);
typedef int (*_EVE_PySet_Update)(PyObject *set, PyObject *iterable);
typedef PyObject * (*_EVEPySlice_New)(PyObject* start, PyObject* stop, PyObject* step);
typedef PyObject * (*_EVE_PySlice_FromIndices)(Py_ssize_t start, Py_ssize_t stop);
typedef int (*_EVEPySlice_GetIndices)(PySliceObject *r, Py_ssize_t length, Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step);
typedef PyObject * (*_EVEPyString_FromStringAndSize)(const char *, Py_ssize_t);
typedef PyObject * (*_EVEPyString_FromString)(const char *);
typedef PyObject * (*_EVEPyString_FromFormatV)(const char*, va_list);
typedef PyObject * (*_EVEPyString_FromFormat)(const char*, ...);
typedef Py_ssize_t (*_EVEPyString_Size)(PyObject *);
typedef char * (*_EVEPyString_AsString)(PyObject *);
typedef PyObject * (*_EVEPyString_Repr)(PyObject *, int);
typedef void (*_EVEPyString_Concat)(PyObject **, PyObject *);
typedef void (*_EVEPyString_ConcatAndDel)(PyObject **, PyObject *);
typedef int (*_EVE_PyString_Resize)(PyObject **, Py_ssize_t);
typedef int (*_EVE_PyString_Eq)(PyObject *, PyObject*);
typedef PyObject * (*_EVEPyString_Format)(PyObject *, PyObject *);
typedef PyObject * (*_EVE_PyString_FormatLong)(PyObject*, int, int, int, char**, int*);
typedef void (*_EVEPyString_InternInPlace)(PyObject **);
typedef void (*_EVEPyString_InternImmortal)(PyObject **);
typedef PyObject * (*_EVEPyString_InternFromString)(const char *);
typedef void (*_EVE_Py_ReleaseInternedStrings)(void);
typedef PyObject * (*_EVE_PyString_Join)(PyObject *sep, PyObject *x);
typedef int (*_EVEPyString_AsStringAndSize)( register PyObject *obj, register char **s, register Py_ssize_t *len);
typedef Py_ssize_t (*_EVE_PyString_InsertThousandsGroupingLocale)(char *buffer, Py_ssize_t n_buffer, char *digits, Py_ssize_t n_digits, Py_ssize_t min_width);
typedef Py_ssize_t (*_EVE_PyString_InsertThousandsGrouping)(char *buffer, Py_ssize_t n_buffer, char *digits, Py_ssize_t n_digits, Py_ssize_t min_width, const char *grouping, const char *thousands_sep);
typedef PyObject * (*_EVE_PyBytes_FormatAdvanced)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len);
typedef PyObject * (*_EVEPyMember_Get)(const char *, struct memberlist *, const char *);
typedef int (*_EVEPyMember_Set)(char *, struct memberlist *, const char *, PyObject *);
typedef PyObject * (*_EVEPyMember_GetOne)(const char *, struct PyMemberDef *);
typedef int (*_EVEPyMember_SetOne)(char *, struct PyMemberDef *, PyObject *);
typedef PyObject * (*_EVEPyStructSequence_New)(PyTypeObject* type);
typedef void (*_EVEPySymtable_Free)(struct symtable *);
typedef PyObject * (*_EVEPySys_GetObject)(char *);
typedef int (*_EVEPySys_SetObject)(char *, PyObject *);
typedef FILE * (*_EVEPySys_GetFile)(char *, FILE *);
typedef void (*_EVEPySys_SetArgv)(int, char **);
typedef void (*_EVEPySys_SetArgvEx)(int, char **, int);
typedef void (*_EVEPySys_SetPath)(char *);
typedef void (*_EVEPySys_WriteStdout)(const char *format, ...);
typedef void (*_EVEPySys_WriteStderr)(const char *format, ...);
typedef void (*_EVEPySys_ResetWarnOptions)(void);
typedef void (*_EVEPySys_AddWarnOption)(char *);
typedef int (*_EVEPySys_HasWarnOptions)(void);
typedef size_t (*_EVE_PySys_GetSizeOf)(PyObject *);
typedef time_t (*_EVE_PyTime_DoubleToTimet)(double x);
typedef double (*_EVE_PyTime_FloatTime)(void);
typedef int (*_EVEPyToken_OneChar)(int);
typedef int (*_EVEPyToken_TwoChars)(int, int);
typedef int (*_EVEPyToken_ThreeChars)(int, int, int);
typedef int (*_EVEPyTraceBack_Here)(struct _frame *);
typedef int (*_EVEPyTraceBack_Print)(PyObject *, PyObject *);
typedef int (*_EVE_Py_DisplaySourceLine)(PyObject *, const char *, int, int);
typedef PyObject * (*_EVEPyTuple_New)(Py_ssize_t size);
typedef Py_ssize_t (*_EVEPyTuple_Size)(PyObject *);
typedef PyObject * (*_EVEPyTuple_GetItem)(PyObject *, Py_ssize_t);
typedef int (*_EVEPyTuple_SetItem)(PyObject *, Py_ssize_t, PyObject *);
typedef PyObject * (*_EVEPyTuple_GetSlice)(PyObject *, Py_ssize_t, Py_ssize_t);
typedef int (*_EVE_PyTuple_Resize)(PyObject **, Py_ssize_t);
typedef PyObject * (*_EVEPyTuple_Pack)(Py_ssize_t, ...);
typedef void (*_EVE_PyTuple_MaybeUntrack)(PyObject *);
typedef int (*_EVEPyTuple_ClearFreeList)(void);
typedef void (*_EVE_PyWarnings_Init)(void);
typedef int (*_EVEPyErr_WarnEx)(PyObject *, const char *, Py_ssize_t);
typedef int (*_EVEPyErr_WarnExplicit)(PyObject *, const char *, const char *, int, const char *, PyObject *);
typedef PyObject * (*_EVEPyWeakref_NewRef)(PyObject *ob, PyObject *callback);
typedef PyObject * (*_EVEPyWeakref_NewProxy)(PyObject *ob, PyObject *callback);
typedef PyObject * (*_EVEPyWeakref_GetObject)(PyObject *ref);
typedef Py_ssize_t (*_EVE_PyWeakref_GetWeakrefCount)(PyWeakReference *head);
typedef void (*_EVE_PyWeakref_ClearRef)(PyWeakReference *self);
typedef PyTaskletObject * (*_EVEPyTasklet_New)(PyTypeObject *type, PyObject *func);
typedef int (*_EVEPyTasklet_Setup)(PyTaskletObject *task, PyObject *args, PyObject *kwds);
typedef int (*_EVEPyTasklet_BindEx)(PyTaskletObject *task, PyObject *func, PyObject *args, PyObject *kwargs);
typedef int (*_EVEPyTasklet_BindThread)(PyTaskletObject *task, long thread_id);
typedef int (*_EVEPyTasklet_Run)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Run_nr)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Switch)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Switch_nr)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Remove)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Insert)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_RaiseException)(PyTaskletObject *self, PyObject *klass, PyObject *args);
typedef int (*_EVEPyTasklet_Throw)(PyTaskletObject *self, int pending, PyObject *exc, PyObject *val, PyObject *tb);
typedef int (*_EVEPyTasklet_Kill)(PyTaskletObject *self);
typedef int (*_EVEPyTasklet_KillEx)(PyTaskletObject *self, int pending);
typedef int (*_EVEPyTasklet_SetAtomic)(PyTaskletObject *task, int flag);
typedef int (*_EVEPyTasklet_SetIgnoreNesting)(PyTaskletObject *task, int flag);
typedef int (*_EVEPyTasklet_GetAtomic)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_GetIgnoreNesting)(PyTaskletObject *task);
typedef PyObject * (*_EVEPyTasklet_GetFrame)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_GetBlockTrap)(PyTaskletObject *task);
typedef void (*_EVEPyTasklet_SetBlockTrap)(PyTaskletObject *task, int value);
typedef int (*_EVEPyTasklet_IsMain)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_IsCurrent)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_GetRecursionDepth)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_GetNestingLevel)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Alive)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Paused)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Scheduled)(PyTaskletObject *task);
typedef int (*_EVEPyTasklet_Restorable)(PyTaskletObject *task);
typedef PyChannelObject * (*_EVEPyChannel_New)(PyTypeObject *type);
typedef int (*_EVEPyChannel_Send)(PyChannelObject *self, PyObject *arg);
typedef int (*_EVEPyChannel_Send_nr)(PyChannelObject *self, PyObject *arg);
typedef PyObject * (*_EVEPyChannel_Receive)(PyChannelObject *self);
typedef PyObject * (*_EVEPyChannel_Receive_nr)(PyChannelObject *self);
typedef int (*_EVEPyChannel_SendException)(PyChannelObject *self, PyObject *klass, PyObject *value);
typedef int (*_EVEPyChannel_SendThrow)(PyChannelObject *self, PyObject *exc, PyObject *val, PyObject *tb);
typedef PyObject * (*_EVEPyChannel_GetQueue)(PyChannelObject *self);
typedef void (*_EVEPyChannel_Close)(PyChannelObject *self);
typedef void (*_EVEPyChannel_Open)(PyChannelObject *self);
typedef int (*_EVEPyChannel_GetClosing)(PyChannelObject *self);
typedef int (*_EVEPyChannel_GetClosed)(PyChannelObject *self);
typedef int (*_EVEPyChannel_GetPreference)(PyChannelObject *self);
typedef void (*_EVEPyChannel_SetPreference)(PyChannelObject *self, int val);
typedef int (*_EVEPyChannel_GetScheduleAll)(PyChannelObject *self);
typedef void (*_EVEPyChannel_SetScheduleAll)(PyChannelObject *self, int val);
typedef int (*_EVEPyChannel_GetBalance)(PyChannelObject *self);
typedef PyObject * (*_EVEPyStackless_Schedule)(PyObject *retval, int remove);
typedef PyObject * (*_EVEPyStackless_Schedule_nr)(PyObject *retval, int remove);
typedef int (*_EVEPyStackless_GetRunCount)(void);
typedef PyObject * (*_EVEPyStackless_GetCurrent)(void);
typedef long (*_EVEPyStackless_GetCurrentId)(void);
typedef PyObject * (*_EVEPyStackless_RunWatchdog)(long timeout);
typedef PyObject * (*_EVEPyStackless_RunWatchdogEx)(long timeout, int flags);
typedef int (*_EVEPyStackless_SetChannelCallback)(PyObject *callable);
typedef int (*_EVEPyStackless_SetScheduleCallback)(PyObject *callable);
typedef void (*_EVEPyStackless_SetScheduleFastcallback)(slp_schedule_hook_func func);
typedef PyObject * (*_EVEPyStackless_Call_Main)(PyObject *func, PyObject *args, PyObject *kwds);
typedef PyObject * (*_EVEPyStackless_CallMethod_Main)(PyObject *o, char *name, char *format, ...);
typedef PyObject * (*_EVEPyStackless_CallCMethod_Main)(PyMethodDef *meth, PyObject *self, char *format, ...);
typedef int (*_EVE_PyStackless_InitTypes)(void);
typedef void (*_EVE_PyStackless_Init)(void);
typedef PyObject * (*_EVEPyEval_EvalFrameEx_slp)(struct _frame *, int, PyObject *);


EXTERNPY(EVEPyObject_Cmp);
EXTERNPY(EVEPyCallable_Check);
EXTERNPY(EVEPyObject_Call);
EXTERNPY(EVEPyObject_CallObject);
EXTERNPY(EVEPyObject_CallFunction);
EXTERNPY(EVEPyObject_CallMethod);
EXTERNPY(EVE_PyObject_CallFunction_SizeT);
EXTERNPY(EVE_PyObject_CallMethod_SizeT);
EXTERNPY(EVEPyObject_CallFunctionObjArgs);
EXTERNPY(EVEPyObject_CallMethodObjArgs);
EXTERNPY(EVEPyObject_Type);
EXTERNPY(EVEPyObject_Size);
EXTERNPY(EVEPyObject_Length);
EXTERNPY(EVE_PyObject_LengthHint);
EXTERNPY(EVEPyObject_GetItem);
EXTERNPY(EVEPyObject_SetItem);
EXTERNPY(EVEPyObject_DelItemString);
EXTERNPY(EVEPyObject_DelItem);
EXTERNPY(EVEPyObject_AsCharBuffer);
EXTERNPY(EVEPyObject_CheckReadBuffer);
EXTERNPY(EVEPyObject_AsReadBuffer);
EXTERNPY(EVEPyObject_AsWriteBuffer);
EXTERNPY(EVEPyObject_GetBuffer);
EXTERNPY(EVEPyBuffer_GetPointer);
EXTERNPY(EVEPyBuffer_SizeFromFormat);
EXTERNPY(EVEPyBuffer_ToContiguous);
EXTERNPY(EVEPyBuffer_FromContiguous);
EXTERNPY(EVEPyObject_CopyData);
EXTERNPY(EVEPyBuffer_IsContiguous);
EXTERNPY(EVEPyBuffer_FillContiguousStrides);
EXTERNPY(EVEPyBuffer_FillInfo);
EXTERNPY(EVEPyBuffer_Release);
EXTERNPY(EVEPyObject_Format);
EXTERNPY(EVEPyObject_GetIter);
EXTERNPY(EVEPyIter_Next);
EXTERNPY(EVEPyNumber_Check);
EXTERNPY(EVEPyNumber_Add);
EXTERNPY(EVEPyNumber_Subtract);
EXTERNPY(EVEPyNumber_Multiply);
EXTERNPY(EVEPyNumber_Divide);
EXTERNPY(EVEPyNumber_FloorDivide);
EXTERNPY(EVEPyNumber_TrueDivide);
EXTERNPY(EVEPyNumber_Remainder);
EXTERNPY(EVEPyNumber_Divmod);
EXTERNPY(EVEPyNumber_Power);
EXTERNPY(EVEPyNumber_Negative);
EXTERNPY(EVEPyNumber_Positive);
EXTERNPY(EVEPyNumber_Absolute);
EXTERNPY(EVEPyNumber_Invert);
EXTERNPY(EVEPyNumber_Lshift);
EXTERNPY(EVEPyNumber_Rshift);
EXTERNPY(EVEPyNumber_And);
EXTERNPY(EVEPyNumber_Xor);
EXTERNPY(EVEPyNumber_Or);
EXTERNPY(EVEPyNumber_Index);
EXTERNPY(EVEPyNumber_AsSsize_t);
EXTERNPY(EVE_PyNumber_ConvertIntegralToInt);
EXTERNPY(EVEPyNumber_Int);
EXTERNPY(EVEPyNumber_Long);
EXTERNPY(EVEPyNumber_Float);
EXTERNPY(EVEPyNumber_InPlaceAdd);
EXTERNPY(EVEPyNumber_InPlaceSubtract);
EXTERNPY(EVEPyNumber_InPlaceMultiply);
EXTERNPY(EVEPyNumber_InPlaceDivide);
EXTERNPY(EVEPyNumber_InPlaceFloorDivide);
EXTERNPY(EVEPyNumber_InPlaceTrueDivide);
EXTERNPY(EVEPyNumber_InPlaceRemainder);
EXTERNPY(EVEPyNumber_InPlacePower);
EXTERNPY(EVEPyNumber_InPlaceLshift);
EXTERNPY(EVEPyNumber_InPlaceRshift);
EXTERNPY(EVEPyNumber_InPlaceAnd);
EXTERNPY(EVEPyNumber_InPlaceXor);
EXTERNPY(EVEPyNumber_InPlaceOr);
EXTERNPY(EVEPyNumber_ToBase);
EXTERNPY(EVEPySequence_Check);
EXTERNPY(EVEPySequence_Size);
EXTERNPY(EVEPySequence_Length);
EXTERNPY(EVEPySequence_Concat);
EXTERNPY(EVEPySequence_Repeat);
EXTERNPY(EVEPySequence_GetItem);
EXTERNPY(EVEPySequence_GetSlice);
EXTERNPY(EVEPySequence_SetItem);
EXTERNPY(EVEPySequence_DelItem);
EXTERNPY(EVEPySequence_SetSlice);
EXTERNPY(EVEPySequence_DelSlice);
EXTERNPY(EVEPySequence_Tuple);
EXTERNPY(EVEPySequence_List);
EXTERNPY(EVEPySequence_Fast);
EXTERNPY(EVEPySequence_Count);
EXTERNPY(EVEPySequence_Contains);
EXTERNPY(EVE_PySequence_IterSearch);
EXTERNPY(EVEPySequence_In);
EXTERNPY(EVEPySequence_Index);
EXTERNPY(EVEPySequence_InPlaceConcat);
EXTERNPY(EVEPySequence_InPlaceRepeat);
EXTERNPY(EVEPyMapping_Check);
EXTERNPY(EVEPyMapping_Size);
EXTERNPY(EVEPyMapping_Length);
EXTERNPY(EVEPyMapping_HasKeyString);
EXTERNPY(EVEPyMapping_HasKey);
EXTERNPY(EVEPyMapping_GetItemString);
EXTERNPY(EVEPyMapping_SetItemString);
EXTERNPY(EVEPyObject_IsInstance);
EXTERNPY(EVEPyObject_IsSubclass);
EXTERNPY(EVE_PyObject_RealIsInstance);
EXTERNPY(EVE_PyObject_RealIsSubclass);
EXTERNPY(EVE_Py_add_one_to_index_F);
EXTERNPY(EVE_Py_add_one_to_index_C);
EXTERNPY(EVEPyBool_FromLong);
EXTERNPY(EVEPyBuffer_FromObject);
EXTERNPY(EVEPyBuffer_FromReadWriteObject);
EXTERNPY(EVEPyBuffer_FromMemory);
EXTERNPY(EVEPyBuffer_FromReadWriteMemory);
EXTERNPY(EVEPyBuffer_New);
EXTERNPY(EVEPyByteArray_FromObject);
EXTERNPY(EVEPyByteArray_Concat);
EXTERNPY(EVEPyByteArray_FromStringAndSize);
EXTERNPY(EVEPyByteArray_Size);
EXTERNPY(EVEPyByteArray_AsString);
EXTERNPY(EVEPyByteArray_Resize);
EXTERNPY(EVEPyCell_New);
EXTERNPY(EVEPyCell_Get);
EXTERNPY(EVEPyCell_Set);
EXTERNPY(EVEPyEval_CallObjectWithKeywords);
EXTERNPY(EVEPyEval_CallFunction);
EXTERNPY(EVEPyEval_CallMethod);
EXTERNPY(EVEPyEval_SetProfile);
EXTERNPY(EVEPyEval_SetTrace);
EXTERNPY(EVEPyEval_GetBuiltins);
EXTERNPY(EVEPyEval_GetGlobals);
EXTERNPY(EVEPyEval_GetLocals);
EXTERNPY(EVEPyEval_GetRestricted);
EXTERNPY(EVEPyEval_MergeCompilerFlags);
EXTERNPY(EVEPy_FlushLine);
EXTERNPY(EVEPy_AddPendingCall);
EXTERNPY(EVEPy_MakePendingCalls);
EXTERNPY(EVEPy_SetRecursionLimit);
EXTERNPY(EVEPy_GetRecursionLimit);
EXTERNPY(EVE_Py_CheckRecursiveCall);
EXTERNPY(EVEPyEval_GetCallStats);
EXTERNPY(EVEPyEval_EvalFrame);
EXTERNPY(EVEPyEval_EvalFrameEx);
EXTERNPY(EVEPyEval_EvalFrame_slp);
EXTERNPY(EVEPyEval_EvalFrameEx_slp);
EXTERNPY(EVEPyEval_SaveThread);
EXTERNPY(EVEPyEval_RestoreThread);
EXTERNPY(EVEPyEval_InitThreads);
EXTERNPY(EVEPyEval_AcquireLock);
EXTERNPY(EVEPyEval_ReleaseLock);
EXTERNPY(EVEPyEval_AcquireThread);
EXTERNPY(EVEPyEval_ReleaseThread);
EXTERNPY(EVEPyEval_ReInitThreads);
EXTERNPY(EVE_PyEval_SliceIndex);
EXTERNPY(EVEPyClass_New);
EXTERNPY(EVEPyInstance_New);
EXTERNPY(EVEPyInstance_NewRaw);
EXTERNPY(EVEPyMethod_New);
EXTERNPY(EVEPyMethod_Function);
EXTERNPY(EVEPyMethod_Self);
EXTERNPY(EVEPyMethod_Class);
EXTERNPY(EVE_PyInstance_Lookup);
EXTERNPY(EVEPyClass_IsSubclass);
EXTERNPY(EVEPyMethod_ClearFreeList);
EXTERNPY(EVEPyCObject_AsVoidPtr);
EXTERNPY(EVEPyCObject_GetDesc);
EXTERNPY(EVEPyCObject_Import);
EXTERNPY(EVEPyCObject_SetVoidPtr);
EXTERNPY(EVEPyCode_New);
EXTERNPY(EVEPyCode_Addr2Line);
EXTERNPY(EVE_PyCode_CheckLineNumber);
EXTERNPY(EVE_PyCode_ConstantKey);
EXTERNPY(EVEPyCode_Optimize);
EXTERNPY(EVEPyCodec_RegisterError);
EXTERNPY(EVEPyCodec_LookupError);
EXTERNPY(EVEPyCodec_StrictErrors);
EXTERNPY(EVEPyCodec_IgnoreErrors);
EXTERNPY(EVEPyCodec_ReplaceErrors);
EXTERNPY(EVEPyCodec_XMLCharRefReplaceErrors);
EXTERNPY(EVEPyCodec_BackslashReplaceErrors);
EXTERNPY(EVEPyNode_Compile);
EXTERNPY(EVEPyAST_Compile);
EXTERNPY(EVEPyFuture_FromAST);
EXTERNPY(EVEPyComplex_FromCComplex);
EXTERNPY(EVEPyComplex_FromDoubles);
EXTERNPY(EVEPyComplex_RealAsDouble);
EXTERNPY(EVEPyComplex_ImagAsDouble);
EXTERNPY(EVEPyComplex_AsCComplex);
EXTERNPY(EVE_PyComplex_FormatAdvanced);
EXTERNPY(EVEPyDescr_NewMethod);
EXTERNPY(EVEPyDescr_NewClassMethod);
EXTERNPY(EVEPyDescr_NewMember);
EXTERNPY(EVEPyDescr_NewGetSet);
EXTERNPY(EVEPyDescr_NewWrapper);
EXTERNPY(EVEPyDictProxy_New);
EXTERNPY(EVEPyWrapper_New);
EXTERNPY(EVEPyDict_New);
EXTERNPY(EVEPyDict_GetItem);
EXTERNPY(EVE_PyDict_GetItemWithError);
EXTERNPY(EVEPyDict_SetItem);
EXTERNPY(EVEPyDict_DelItem);
EXTERNPY(EVEPyDict_Clear);
EXTERNPY(EVEPyDict_Next);
EXTERNPY(EVE_PyDict_Next);
EXTERNPY(EVEPyDict_Keys);
EXTERNPY(EVEPyDict_Values);
EXTERNPY(EVEPyDict_Items);
EXTERNPY(EVEPyDict_Size);
EXTERNPY(EVEPyDict_Copy);
EXTERNPY(EVEPyDict_Contains);
EXTERNPY(EVE_PyDict_Contains);
EXTERNPY(EVE_PyDict_NewPresized);
EXTERNPY(EVE_PyDict_MaybeUntrack);
EXTERNPY(EVEPyDict_Update);
EXTERNPY(EVEPyDict_Merge);
EXTERNPY(EVEPyDict_MergeFromSeq2);
EXTERNPY(EVEPyDict_GetItemString);
EXTERNPY(EVEPyDict_SetItemString);
EXTERNPY(EVEPyDict_DelItemString);
EXTERNPY(EVE_Py_dg_strtod);
EXTERNPY(EVE_Py_dg_dtoa);
EXTERNPY(EVE_Py_dg_freedtoa);
EXTERNPY(EVEPyEval_EvalCode);
EXTERNPY(EVEPyEval_EvalCodeEx);
EXTERNPY(EVE_PyEval_CallTracing);
EXTERNPY(EVEPyFile_FromString);
EXTERNPY(EVEPyFile_SetBufSize);
EXTERNPY(EVEPyFile_SetEncoding);
EXTERNPY(EVEPyFile_SetEncodingAndErrors);
EXTERNPY(EVEPyFile_FromFile);
EXTERNPY(EVEPyFile_AsFile);
EXTERNPY(EVEPyFile_IncUseCount);
EXTERNPY(EVEPyFile_DecUseCount);
EXTERNPY(EVEPyFile_Name);
EXTERNPY(EVEPyFile_GetLine);
EXTERNPY(EVEPyFile_WriteObject);
EXTERNPY(EVEPyFile_SoftSpace);
EXTERNPY(EVEPyFile_WriteString);
EXTERNPY(EVEPyObject_AsFileDescriptor);
EXTERNPY(EVEPyFloat_GetMax);
EXTERNPY(EVEPyFloat_GetMin);
EXTERNPY(EVEPyFloat_GetInfo);
EXTERNPY(EVEPyFloat_FromString);
EXTERNPY(EVEPyFloat_FromDouble);
EXTERNPY(EVEPyFloat_AsDouble);
EXTERNPY(EVEPyFloat_AsReprString);
EXTERNPY(EVEPyFloat_AsString);
EXTERNPY(EVE_PyFloat_Pack4);
EXTERNPY(EVE_PyFloat_Pack8);
EXTERNPY(EVE_PyFloat_Digits);
EXTERNPY(EVE_PyFloat_DigitsInit);
EXTERNPY(EVE_PyFloat_Unpack4);
EXTERNPY(EVE_PyFloat_Unpack8);
EXTERNPY(EVEPyFloat_ClearFreeList);
EXTERNPY(EVE_PyFloat_FormatAdvanced);
EXTERNPY(EVE_Py_double_round);
EXTERNPY(EVEPyFrame_New);
EXTERNPY(EVEPyFrame_BlockSetup);
EXTERNPY(EVEPyFrame_BlockPop);
EXTERNPY(EVEPyFrame_ExtendStack);
EXTERNPY(EVEPyFrame_LocalsToFast);
EXTERNPY(EVEPyFrame_FastToLocals);
EXTERNPY(EVEPyFrame_ClearFreeList);
EXTERNPY(EVEPyFrame_GetLineNumber);
EXTERNPY(EVEPyFunction_New);
EXTERNPY(EVEPyFunction_GetCode);
EXTERNPY(EVEPyFunction_GetGlobals);
EXTERNPY(EVEPyFunction_GetModule);
EXTERNPY(EVEPyFunction_GetDefaults);
EXTERNPY(EVEPyFunction_SetDefaults);
EXTERNPY(EVEPyFunction_GetClosure);
EXTERNPY(EVEPyFunction_SetClosure);
EXTERNPY(EVEPyClassMethod_New);
EXTERNPY(EVEPyStaticMethod_New);
EXTERNPY(EVEPyGen_New);
EXTERNPY(EVEPyGen_NeedsFinalizing);
EXTERNPY(EVEPyImport_GetMagicNumber);
EXTERNPY(EVEPyImport_ExecCodeModule);
EXTERNPY(EVEPyImport_ExecCodeModuleEx);
EXTERNPY(EVEPyImport_GetModuleDict);
EXTERNPY(EVEPyImport_AddModule);
EXTERNPY(EVEPyImport_ImportModule);
EXTERNPY(EVEPyImport_ImportModuleNoBlock);
EXTERNPY(EVEPyImport_ImportModuleLevel);
EXTERNPY(EVEPyImport_GetImporter);
EXTERNPY(EVEPyImport_Import);
EXTERNPY(EVEPyImport_ReloadModule);
EXTERNPY(EVEPyImport_Cleanup);
EXTERNPY(EVEPyImport_ImportFrozenModule);
EXTERNPY(EVE_PyImport_AcquireLock);
EXTERNPY(EVE_PyImport_ReleaseLock);
EXTERNPY(EVE_PyImport_IsScript);
EXTERNPY(EVE_PyImport_ReInitLock);
EXTERNPY(EVE_PyImport_FindExtension);
EXTERNPY(EVE_PyImport_FixupExtension);
EXTERNPY(EVEPyInt_FromString);
EXTERNPY(EVEPyInt_FromUnicode);
EXTERNPY(EVEPyInt_FromLong);
EXTERNPY(EVEPyInt_FromSize_t);
EXTERNPY(EVEPyInt_FromSsize_t);
EXTERNPY(EVEPyInt_AsLong);
EXTERNPY(EVEPyInt_AsSsize_t);
EXTERNPY(EVE_PyInt_AsInt);
EXTERNPY(EVEPyInt_GetMax);
EXTERNPY(EVEPyOS_strtol);
EXTERNPY(EVEPyInt_ClearFreeList);
EXTERNPY(EVE_PyInt_Format);
EXTERNPY(EVE_PyInt_FormatAdvanced);
EXTERNPY(EVEPyOS_InterruptOccurred);
EXTERNPY(EVEPyOS_InitInterrupts);
EXTERNPY(EVEPyOS_AfterFork);
EXTERNPY(EVEPySeqIter_New);
EXTERNPY(EVEPyCallIter_New);
EXTERNPY(EVEPyList_New);
EXTERNPY(EVEPyList_Size);
EXTERNPY(EVEPyList_GetItem);
EXTERNPY(EVEPyList_SetItem);
EXTERNPY(EVEPyList_Insert);
EXTERNPY(EVEPyList_Append);
EXTERNPY(EVEPyList_GetSlice);
EXTERNPY(EVEPyList_SetSlice);
EXTERNPY(EVEPyList_Sort);
EXTERNPY(EVEPyList_Reverse);
EXTERNPY(EVEPyList_AsTuple);
EXTERNPY(EVE_PyList_Extend);
EXTERNPY(EVE_PyLong_New);
EXTERNPY(EVE_PyLong_Copy);
EXTERNPY(EVEPyLong_FromLong);
EXTERNPY(EVEPyLong_FromUnsignedLong);
EXTERNPY(EVEPyLong_FromDouble);
EXTERNPY(EVEPyLong_FromSize_t);
EXTERNPY(EVEPyLong_FromSsize_t);
EXTERNPY(EVEPyLong_AsLong);
EXTERNPY(EVEPyLong_AsLongAndOverflow);
EXTERNPY(EVEPyLong_AsSsize_t);
EXTERNPY(EVE_PyLong_AsInt);
EXTERNPY(EVEPyLong_GetInfo);
EXTERNPY(EVE_PyLong_Frexp);
EXTERNPY(EVEPyLong_AsDouble);
EXTERNPY(EVEPyLong_FromVoidPtr);
EXTERNPY(EVEPyLong_AsVoidPtr);
EXTERNPY(EVEPyLong_FromLongLong);
EXTERNPY(EVEPyLong_FromUnsignedLongLong);
EXTERNPY(EVEPyLong_AsLongLong);
EXTERNPY(EVEPyLong_AsLongLongAndOverflow);
EXTERNPY(EVEPyLong_FromString);
EXTERNPY(EVEPyLong_FromUnicode);
EXTERNPY(EVE_PyLong_Sign);
EXTERNPY(EVE_PyLong_NumBits);
EXTERNPY(EVE_PyLong_FromByteArray);
EXTERNPY(EVE_PyLong_AsByteArray);
EXTERNPY(EVE_PyLong_Format);
EXTERNPY(EVE_PyLong_FormatAdvanced);
EXTERNPY(EVEPyMarshal_WriteLongToFile);
EXTERNPY(EVEPyMarshal_WriteObjectToFile);
EXTERNPY(EVEPyMarshal_WriteObjectToString);
EXTERNPY(EVEPyMarshal_ReadLongFromFile);
EXTERNPY(EVEPyMarshal_ReadShortFromFile);
EXTERNPY(EVEPyMarshal_ReadObjectFromFile);
EXTERNPY(EVEPyMarshal_ReadLastObjectFromFile);
EXTERNPY(EVEPyMarshal_ReadObjectFromString);
EXTERNPY(EVEPyCFunction_GetFunction);
EXTERNPY(EVEPyCFunction_GetSelf);
EXTERNPY(EVEPyCFunction_GetFlags);
EXTERNPY(EVEPyCFunction_Call);
EXTERNPY(EVEPy_FindMethod);
EXTERNPY(EVEPyCFunction_ClearFreeList);
EXTERNPY(EVE_Py_VaBuildValue_SizeT);
EXTERNPY(EVEPyArg_Parse);
EXTERNPY(EVEPyArg_ParseTuple);
EXTERNPY(EVEPyArg_ParseTupleAndKeywords);
EXTERNPY(EVEPyArg_UnpackTuple);
EXTERNPY(EVEPy_BuildValue);
EXTERNPY(EVE_Py_BuildValue_SizeT);
EXTERNPY(EVE_PyArg_NoKeywords);
EXTERNPY(EVEPyArg_VaParse);
EXTERNPY(EVEPyArg_VaParseTupleAndKeywords);
EXTERNPY(EVEPy_VaBuildValue);
EXTERNPY(EVEPyModule_AddObject);
EXTERNPY(EVEPyModule_AddIntConstant);
EXTERNPY(EVEPyModule_AddStringConstant);
EXTERNPY(EVEPy_InitModule4);
EXTERNPY(EVEPyModule_New);
EXTERNPY(EVEPyModule_GetDict);
EXTERNPY(EVEPyModule_GetName);
EXTERNPY(EVEPyModule_GetFilename);
EXTERNPY(EVE_PyModule_Clear);
EXTERNPY(EVEPyType_IsSubtype);
EXTERNPY(EVEPyType_Ready);
EXTERNPY(EVEPyType_GenericAlloc);
EXTERNPY(EVEPyType_GenericNew);
EXTERNPY(EVE_PyType_Lookup);
EXTERNPY(EVE_PyObject_LookupSpecial);
EXTERNPY(EVEPyType_Modified);
EXTERNPY(EVEPyObject_Print);
EXTERNPY(EVE_PyObject_Dump);
EXTERNPY(EVEPyObject_Repr);
EXTERNPY(EVE_PyObject_Str);
EXTERNPY(EVEPyObject_Str);
EXTERNPY(EVEPyObject_Unicode);
EXTERNPY(EVEPyObject_Compare);
EXTERNPY(EVEPyObject_RichCompare);
EXTERNPY(EVEPyObject_RichCompareBool);
EXTERNPY(EVEPyObject_GetAttrString);
EXTERNPY(EVEPyObject_SetAttrString);
EXTERNPY(EVEPyObject_HasAttrString);
EXTERNPY(EVEPyObject_GetAttr);
EXTERNPY(EVEPyObject_SetAttr);
EXTERNPY(EVEPyObject_HasAttr);
EXTERNPY(EVE_PyObject_GetDictPtr);
EXTERNPY(EVEPyObject_SelfIter);
EXTERNPY(EVE_PyObject_NextNotImplemented);
EXTERNPY(EVEPyObject_GenericGetAttr);
EXTERNPY(EVEPyObject_GenericSetAttr);
EXTERNPY(EVEPyObject_Hash);
EXTERNPY(EVEPyObject_HashNotImplemented);
EXTERNPY(EVEPyObject_IsTrue);
EXTERNPY(EVEPyObject_Not);
EXTERNPY(EVEPyCallable_Check);
EXTERNPY(EVEPyNumber_Coerce);
EXTERNPY(EVEPyNumber_CoerceEx);
EXTERNPY(EVEPyObject_ClearWeakRefs);
EXTERNPY(EVEPyObject_Dir);
EXTERNPY(EVEPy_ReprEnter);
EXTERNPY(EVEPy_ReprLeave);
EXTERNPY(EVE_Py_HashDouble);
EXTERNPY(EVE_Py_HashPointer);
EXTERNPY(EVE_Py_NegativeRefcount);
EXTERNPY(EVE_PyDict_Dummy);
EXTERNPY(EVE_PySet_Dummy);
EXTERNPY(EVE_Py_GetRefTotal);
EXTERNPY(EVEinc_count);
EXTERNPY(EVEdec_count);
EXTERNPY(EVE_Py_NewReference);
EXTERNPY(EVE_Py_ForgetReference);
EXTERNPY(EVE_Py_Dealloc);
EXTERNPY(EVE_Py_PrintReferences);
EXTERNPY(EVE_Py_PrintReferenceAddresses);
EXTERNPY(EVE_Py_AddToAllObjects);
EXTERNPY(EVEPy_IncRef);
EXTERNPY(EVEPy_DecRef);
EXTERNPY(EVE_PyTrash_deposit_object);
EXTERNPY(EVE_PyTrash_destroy_chain);
EXTERNPY(EVE_PyTrash_thread_deposit_object);
EXTERNPY(EVE_PyTrash_thread_destroy_chain);
EXTERNPY(EVEPyObject_Malloc);
EXTERNPY(EVEPyObject_Realloc);
EXTERNPY(EVEPyObject_Free);
EXTERNPY(EVE_PyObject_DebugMalloc);
EXTERNPY(EVE_PyObject_DebugRealloc);
EXTERNPY(EVE_PyObject_DebugFree);
EXTERNPY(EVE_PyObject_DebugDumpAddress);
EXTERNPY(EVE_PyObject_DebugCheckAddress);
EXTERNPY(EVE_PyObject_DebugMallocStats);
EXTERNPY(EVE_PyObject_DebugMallocApi);
EXTERNPY(EVE_PyObject_DebugReallocApi);
EXTERNPY(EVE_PyObject_DebugFreeApi);
EXTERNPY(EVE_PyObject_DebugCheckAddressApi);
EXTERNPY(EVE_PyMem_DebugMalloc);
EXTERNPY(EVE_PyMem_DebugRealloc);
EXTERNPY(EVE_PyMem_DebugFree);
EXTERNPY(EVEPyObject_Init);
EXTERNPY(EVEPyObject_InitVar);
EXTERNPY(EVE_PyObject_New);
EXTERNPY(EVE_PyObject_NewVar);
EXTERNPY(EVEPyGC_Collect);
EXTERNPY(EVE_PyObject_GC_Resize);
EXTERNPY(EVE_PyObject_GC_Malloc);
EXTERNPY(EVE_PyObject_GC_New);
EXTERNPY(EVE_PyObject_GC_NewVar);
EXTERNPY(EVEPyObject_GC_Track);
EXTERNPY(EVEPyObject_GC_UnTrack);
EXTERNPY(EVEPyObject_GC_Del);
EXTERNPY(EVEPyObject_GC_Collectable);
EXTERNPY(EVEPySys_WriteStdout);
EXTERNPY(EVEPySys_WriteStderr);
EXTERNPY(EVEPyArena_New);
EXTERNPY(EVEPyArena_Free);
EXTERNPY(EVEPyArena_Malloc);
EXTERNPY(EVEPyArena_AddPyObject);
EXTERNPY(EVEPyCapsule_New);
EXTERNPY(EVEPyCapsule_GetPointer);
EXTERNPY(EVEPyCapsule_GetDestructor);
EXTERNPY(EVEPyCapsule_GetContext);
EXTERNPY(EVEPyCapsule_IsValid);
EXTERNPY(EVEPyCapsule_SetPointer);
EXTERNPY(EVEPyCapsule_SetDestructor);
EXTERNPY(EVEPyCapsule_SetName);
EXTERNPY(EVEPyCapsule_SetContext);
EXTERNPY(EVEPyCapsule_Import);
EXTERNPY(EVEPy_FatalError);
EXTERNPY(EVEPyErr_SetNone);
EXTERNPY(EVEPyErr_SetObject);
EXTERNPY(EVEPyErr_SetString);
EXTERNPY(EVEPyErr_Occurred);
EXTERNPY(EVEPyErr_Clear);
EXTERNPY(EVEPyErr_Fetch);
EXTERNPY(EVEPyErr_Restore);
EXTERNPY(EVEPyErr_GivenExceptionMatches);
EXTERNPY(EVEPyErr_ExceptionMatches);
EXTERNPY(EVEPyErr_NormalizeException);
EXTERNPY(EVE_PyErr_ReplaceException);
EXTERNPY(EVEPyErr_BadArgument);
EXTERNPY(EVEPyErr_NoMemory);
EXTERNPY(EVEPyErr_SetFromErrno);
EXTERNPY(EVEPyErr_SetFromErrnoWithFilenameObject);
EXTERNPY(EVEPyErr_SetFromErrnoWithFilename);
EXTERNPY(EVEPyErr_SetFromErrnoWithUnicodeFilename);
EXTERNPY(EVEPyErr_Format);
EXTERNPY(EVEPyErr_SetFromWindowsErrWithFilenameObject);
EXTERNPY(EVEPyErr_SetFromWindowsErrWithFilename);
EXTERNPY(EVEPyErr_SetFromWindowsErrWithUnicodeFilename);
EXTERNPY(EVEPyErr_SetFromWindowsErr);
EXTERNPY(EVEPyErr_SetExcFromWindowsErrWithFilenameObject);
EXTERNPY(EVEPyErr_SetExcFromWindowsErrWithFilename);
EXTERNPY(EVEPyErr_SetExcFromWindowsErrWithUnicodeFilename);
EXTERNPY(EVEPyErr_SetExcFromWindowsErr);
EXTERNPY(EVEPyErr_BadInternalCall);
EXTERNPY(EVE_PyErr_BadInternalCall);
EXTERNPY(EVEPyErr_NewException);
EXTERNPY(EVEPyErr_NewExceptionWithDoc);
EXTERNPY(EVEPyErr_WriteUnraisable);
EXTERNPY(EVEPyErr_CheckSignals);
EXTERNPY(EVEPyErr_SetInterrupt);
EXTERNPY(EVEPyErr_SyntaxLocation);
EXTERNPY(EVEPyErr_ProgramText);
EXTERNPY(EVEPyUnicodeDecodeError_Create);
EXTERNPY(EVEPyUnicodeEncodeError_Create);
EXTERNPY(EVEPyUnicodeTranslateError_Create);
EXTERNPY(EVEPyUnicodeEncodeError_GetEncoding);
EXTERNPY(EVEPyUnicodeDecodeError_GetEncoding);
EXTERNPY(EVEPyUnicodeEncodeError_GetObject);
EXTERNPY(EVEPyUnicodeDecodeError_GetObject);
EXTERNPY(EVEPyUnicodeTranslateError_GetObject);
EXTERNPY(EVEPyUnicodeEncodeError_GetStart);
EXTERNPY(EVEPyUnicodeDecodeError_GetStart);
EXTERNPY(EVEPyUnicodeTranslateError_GetStart);
EXTERNPY(EVEPyUnicodeEncodeError_SetStart);
EXTERNPY(EVEPyUnicodeDecodeError_SetStart);
EXTERNPY(EVEPyUnicodeTranslateError_SetStart);
EXTERNPY(EVEPyUnicodeEncodeError_GetEnd);
EXTERNPY(EVEPyUnicodeDecodeError_GetEnd);
EXTERNPY(EVEPyUnicodeTranslateError_GetEnd);
EXTERNPY(EVEPyUnicodeEncodeError_SetEnd);
EXTERNPY(EVEPyUnicodeDecodeError_SetEnd);
EXTERNPY(EVEPyUnicodeTranslateError_SetEnd);
EXTERNPY(EVEPyUnicodeEncodeError_GetReason);
EXTERNPY(EVEPyUnicodeDecodeError_GetReason);
EXTERNPY(EVEPyUnicodeTranslateError_GetReason);
EXTERNPY(EVEPyUnicodeEncodeError_SetReason);
EXTERNPY(EVEPyUnicodeDecodeError_SetReason);
EXTERNPY(EVEPyUnicodeTranslateError_SetReason);
EXTERNPY(EVEPyOS_snprintf);
EXTERNPY(EVEPyOS_vsnprintf);
EXTERNPY(EVE_PyOS_ResetGetOpt);
EXTERNPY(EVE_PyOS_GetOpt);
EXTERNPY(EVE_Py_force_double);
EXTERNPY(EVE_Py_set_387controlword);
EXTERNPY(EVEPyMem_Malloc);
EXTERNPY(EVEPyMem_Realloc);
EXTERNPY(EVEPyMem_Free);
EXTERNPY(EVEPyInterpreterState_New);
EXTERNPY(EVEPyInterpreterState_Clear);
EXTERNPY(EVEPyInterpreterState_Delete);
EXTERNPY(EVEPyThreadState_New);
EXTERNPY(EVE_PyThreadState_Prealloc);
EXTERNPY(EVE_PyThreadState_Init);
EXTERNPY(EVEPyThreadState_Clear);
EXTERNPY(EVEPyThreadState_Delete);
EXTERNPY(EVEPyThreadState_DeleteCurrent);
EXTERNPY(EVEPyThreadState_Get);
EXTERNPY(EVEPyThreadState_Swap);
EXTERNPY(EVEPyThreadState_GetDict);
EXTERNPY(EVEPyThreadState_SetAsyncExc);
EXTERNPY(EVEPyGILState_Ensure);
EXTERNPY(EVEPyGILState_Release);
EXTERNPY(EVEPyGILState_GetThisThreadState);
EXTERNPY(EVE_PyThread_CurrentFrames);
EXTERNPY(EVEPyInterpreterState_Head);
EXTERNPY(EVEPyInterpreterState_Next);
EXTERNPY(EVEPyInterpreterState_ThreadHead);
EXTERNPY(EVEPyThreadState_Next);
EXTERNPY(EVEPyOS_mystrnicmp);
EXTERNPY(EVEPyOS_mystricmp);
EXTERNPY(EVEPyOS_ascii_strtod);
EXTERNPY(EVEPyOS_ascii_atof);
EXTERNPY(EVEPyOS_ascii_formatd);
EXTERNPY(EVEPyOS_string_to_double);
EXTERNPY(EVEPyOS_double_to_string);
EXTERNPY(EVE_Py_parse_inf_or_nan);
EXTERNPY(EVE_Py_Mangle);
EXTERNPY(EVEPy_SetProgramName);
EXTERNPY(EVEPy_GetProgramName);
EXTERNPY(EVEPy_SetPythonHome);
EXTERNPY(EVEPy_GetPythonHome);
EXTERNPY(EVEPy_Initialize);
EXTERNPY(EVEPy_InitializeEx);
EXTERNPY(EVEPy_Finalize);
EXTERNPY(EVEPy_IsInitialized);
EXTERNPY(EVEPy_NewInterpreter);
EXTERNPY(EVEPy_EndInterpreter);
EXTERNPY(EVEPyRun_AnyFileFlags);
EXTERNPY(EVEPyRun_AnyFileExFlags);
EXTERNPY(EVEPyRun_SimpleStringFlags);
EXTERNPY(EVEPyRun_SimpleFileExFlags);
EXTERNPY(EVEPyRun_InteractiveOneFlags);
EXTERNPY(EVEPyRun_InteractiveLoopFlags);
EXTERNPY(EVEPy_CompileStringFlags);
EXTERNPY(EVEPyErr_Print);
EXTERNPY(EVEPyErr_PrintEx);
EXTERNPY(EVEPyErr_Display);
EXTERNPY(EVEPy_AtExit);
EXTERNPY(EVEPy_Exit);
EXTERNPY(EVEPy_FdIsInteractive);
EXTERNPY(EVEPy_Main);
EXTERNPY(EVEPy_GetProgramFullPath);
EXTERNPY(EVEPy_GetPrefix);
EXTERNPY(EVEPy_GetExecPrefix);
EXTERNPY(EVEPy_GetPath);
EXTERNPY(EVE_PyBuiltin_Init);
EXTERNPY(EVE_PySys_Init);
EXTERNPY(EVE_PyImport_Init);
EXTERNPY(EVE_PyExc_Init);
EXTERNPY(EVE_PyImportHooks_Init);
EXTERNPY(EVE_PyFrame_Init);
EXTERNPY(EVE_PyInt_Init);
EXTERNPY(EVE_PyLong_Init);
EXTERNPY(EVE_PyFloat_Init);
EXTERNPY(EVEPyByteArray_Init);
EXTERNPY(EVE_PyRandom_Init);
EXTERNPY(EVE_PyExc_Fini);
EXTERNPY(EVE_PyImport_Fini);
EXTERNPY(EVEPyMethod_Fini);
EXTERNPY(EVEPyFrame_Fini);
EXTERNPY(EVEPyCFunction_Fini);
EXTERNPY(EVEPyDict_Fini);
EXTERNPY(EVEPyTuple_Fini);
EXTERNPY(EVEPyList_Fini);
EXTERNPY(EVEPySet_Fini);
EXTERNPY(EVEPyString_Fini);
EXTERNPY(EVEPyInt_Fini);
EXTERNPY(EVEPyFloat_Fini);
EXTERNPY(EVEPyOS_FiniInterrupts);
EXTERNPY(EVEPyByteArray_Fini);
EXTERNPY(EVE_PyRandom_Fini);
EXTERNPY(EVEPyOS_Readline);
EXTERNPY(EVEPyOS_CheckStack);
EXTERNPY(EVEPyOS_getsig);
EXTERNPY(EVEPyOS_setsig);
EXTERNPY(EVE_PyOS_URandom);
EXTERNPY(EVEPySet_New);
EXTERNPY(EVEPyFrozenSet_New);
EXTERNPY(EVEPySet_Size);
EXTERNPY(EVEPySet_Clear);
EXTERNPY(EVEPySet_Contains);
EXTERNPY(EVEPySet_Discard);
EXTERNPY(EVEPySet_Add);
EXTERNPY(EVE_PySet_Next);
EXTERNPY(EVE_PySet_NextEntry);
EXTERNPY(EVEPySet_Pop);
EXTERNPY(EVE_PySet_Update);
EXTERNPY(EVEPySlice_New);
EXTERNPY(EVE_PySlice_FromIndices);
EXTERNPY(EVEPySlice_GetIndices);
EXTERNPY(EVEPyString_FromStringAndSize);
EXTERNPY(EVEPyString_FromString);
EXTERNPY(EVEPyString_FromFormatV);
EXTERNPY(EVEPyString_FromFormat);
EXTERNPY(EVEPyString_Size);
EXTERNPY(EVEPyString_AsString);
EXTERNPY(EVEPyString_Repr);
EXTERNPY(EVEPyString_Concat);
EXTERNPY(EVEPyString_ConcatAndDel);
EXTERNPY(EVE_PyString_Resize);
EXTERNPY(EVE_PyString_Eq);
EXTERNPY(EVEPyString_Format);
EXTERNPY(EVE_PyString_FormatLong);
EXTERNPY(EVEPyString_InternInPlace);
EXTERNPY(EVEPyString_InternImmortal);
EXTERNPY(EVEPyString_InternFromString);
EXTERNPY(EVE_Py_ReleaseInternedStrings);
EXTERNPY(EVE_PyString_Join);
EXTERNPY(EVEPyString_AsStringAndSize);
EXTERNPY(EVE_PyString_InsertThousandsGroupingLocale);
EXTERNPY(EVE_PyString_InsertThousandsGrouping);
EXTERNPY(EVE_PyBytes_FormatAdvanced);
EXTERNPY(EVEPyMember_Get);
EXTERNPY(EVEPyMember_Set);
EXTERNPY(EVEPyMember_GetOne);
EXTERNPY(EVEPyMember_SetOne);
EXTERNPY(EVEPySys_GetObject);
EXTERNPY(EVEPySys_SetObject);
EXTERNPY(EVEPySys_GetFile);
EXTERNPY(EVEPySys_SetArgv);
EXTERNPY(EVEPySys_SetArgvEx);
EXTERNPY(EVEPySys_SetPath);
EXTERNPY(EVEPySys_WriteStdout);
EXTERNPY(EVEPySys_WriteStderr);
EXTERNPY(EVEPySys_ResetWarnOptions);
EXTERNPY(EVEPySys_AddWarnOption);
EXTERNPY(EVEPySys_HasWarnOptions);
EXTERNPY(EVE_PySys_GetSizeOf);
EXTERNPY(EVE_PyTime_DoubleToTimet);
EXTERNPY(EVE_PyTime_FloatTime);
EXTERNPY(EVEPyToken_OneChar);
EXTERNPY(EVEPyToken_TwoChars);
EXTERNPY(EVEPyToken_ThreeChars);
EXTERNPY(EVEPyTraceBack_Here);
EXTERNPY(EVEPyTraceBack_Print);
EXTERNPY(EVE_Py_DisplaySourceLine);
EXTERNPY(EVEPyTuple_New);
EXTERNPY(EVEPyTuple_Size);
EXTERNPY(EVEPyTuple_GetItem);
EXTERNPY(EVEPyTuple_SetItem);
EXTERNPY(EVEPyTuple_GetSlice);
EXTERNPY(EVE_PyTuple_Resize);
EXTERNPY(EVEPyTuple_Pack);
EXTERNPY(EVE_PyTuple_MaybeUntrack);
EXTERNPY(EVEPyTuple_ClearFreeList);
EXTERNPY(EVE_PyWarnings_Init);
EXTERNPY(EVEPyErr_WarnEx);
EXTERNPY(EVEPyErr_WarnExplicit);
EXTERNPY(EVEPyWeakref_NewRef);
EXTERNPY(EVEPyWeakref_NewProxy);
EXTERNPY(EVEPyWeakref_GetObject);
EXTERNPY(EVE_PyWeakref_GetWeakrefCount);
EXTERNPY(EVE_PyWeakref_ClearRef);
EXTERNPY(EVEPyTasklet_New);
EXTERNPY(EVEPyTasklet_Setup);
EXTERNPY(EVEPyTasklet_BindEx);
EXTERNPY(EVEPyTasklet_BindThread);
EXTERNPY(EVEPyTasklet_Run);
EXTERNPY(EVEPyTasklet_Run_nr);
EXTERNPY(EVEPyTasklet_Switch);
EXTERNPY(EVEPyTasklet_Switch_nr);
EXTERNPY(EVEPyTasklet_Remove);
EXTERNPY(EVEPyTasklet_Insert);
EXTERNPY(EVEPyTasklet_RaiseException);
EXTERNPY(EVEPyTasklet_Throw);
EXTERNPY(EVEPyTasklet_Kill);
EXTERNPY(EVEPyTasklet_KillEx);
EXTERNPY(EVEPyTasklet_SetAtomic);
EXTERNPY(EVEPyTasklet_SetIgnoreNesting);
EXTERNPY(EVEPyTasklet_GetAtomic);
EXTERNPY(EVEPyTasklet_GetIgnoreNesting);
EXTERNPY(EVEPyTasklet_GetFrame);
EXTERNPY(EVEPyTasklet_GetBlockTrap);
EXTERNPY(EVEPyTasklet_SetBlockTrap);
EXTERNPY(EVEPyTasklet_IsMain);
EXTERNPY(EVEPyTasklet_IsCurrent);
EXTERNPY(EVEPyTasklet_GetRecursionDepth);
EXTERNPY(EVEPyTasklet_GetNestingLevel);
EXTERNPY(EVEPyTasklet_Alive);
EXTERNPY(EVEPyTasklet_Paused);
EXTERNPY(EVEPyTasklet_Scheduled);
EXTERNPY(EVEPyTasklet_Restorable);
EXTERNPY(EVEPyChannel_New);
EXTERNPY(EVEPyChannel_Send);
EXTERNPY(EVEPyChannel_Send_nr);
EXTERNPY(EVEPyChannel_Receive);
EXTERNPY(EVEPyChannel_Receive_nr);
EXTERNPY(EVEPyChannel_SendException);
EXTERNPY(EVEPyChannel_SendThrow);
EXTERNPY(EVEPyChannel_GetQueue);
EXTERNPY(EVEPyChannel_Close);
EXTERNPY(EVEPyChannel_Open);
EXTERNPY(EVEPyChannel_GetClosing);
EXTERNPY(EVEPyChannel_GetClosed);
EXTERNPY(EVEPyChannel_GetPreference);
EXTERNPY(EVEPyChannel_SetPreference);
EXTERNPY(EVEPyChannel_GetScheduleAll);
EXTERNPY(EVEPyChannel_SetScheduleAll);
EXTERNPY(EVEPyChannel_GetBalance);
EXTERNPY(EVEPyStackless_Schedule);
EXTERNPY(EVEPyStackless_Schedule_nr);
EXTERNPY(EVEPyStackless_GetRunCount);
EXTERNPY(EVEPyStackless_GetCurrent);
EXTERNPY(EVEPyStackless_GetCurrentId);
EXTERNPY(EVEPyStackless_RunWatchdog);
EXTERNPY(EVEPyStackless_RunWatchdogEx);
EXTERNPY(EVEPyStackless_SetChannelCallback);
EXTERNPY(EVEPyStackless_SetScheduleCallback);
EXTERNPY(EVEPyStackless_SetScheduleFastcallback);
EXTERNPY(EVEPyStackless_Call_Main);
EXTERNPY(EVEPyStackless_CallMethod_Main);
EXTERNPY(EVEPyStackless_CallCMethod_Main);
EXTERNPY(EVE_PyStackless_InitTypes);
EXTERNPY(EVE_PyStackless_Init);
EXTERNPY(EVEPyEval_EvalFrameEx_slp);
