//
// Created by Nick on 10/21/2021.
//

#ifndef EVELOADER2_BLUE_PATCHER_H
#define EVELOADER2_BLUE_PATCHER_H

#define CRUCIBLE_BLUE_DLL_CRC32 0x965BDFFD
#define CRUCIBLE_BLUE_STSCHAKE_DLL_CRC32 0x5DEB44AE

void check_blue_patch();

#endif //EVELOADER2_BLUE_PATCHER_H
